### ISSUE TITLE
Print/export to PDF doesn't work properly

### ISSUE THREAD

**Issue by sikmir** [tumic0/GPXSee#107]
I've tried to print (via virtual PDF printer) and export-to-PDF, but neither way works for me.
Let's get [some track file](http://www.gpsies.com/map.do?fileId=qvgsiaplvzfrvwrr) for example. And here are some outputs with different background maps: [1.pdf](https://github.com/tumic0/GPXSee/files/1944141/1.pdf) (OSM), [2.pdf](https://github.com/tumic0/GPXSee/files/1944142/2.pdf) (Heidelberg), [3.pdf](https://github.com/tumic0/GPXSee/files/1944144/3.pdf) (OpenTopoMap). As you can see background map is almost blank, even though all map tiles were loaded and displayed in GPXSee.

**Comment by tumic0** [comment]
Some more info is required as I can not reproduce the issue. Print/Export works fine for me (both WYSIWYG and "high resolution"). Do you have the latest GPXSee version? Is it some official build? What Qt version do you have?

**Comment by sikmir** [comment]
GPXSee 5.9 ([archlinux package](https://www.archlinux.org/packages/community/x86_64/gpxsee/)), Qt 5.10.1.

**Comment by sikmir** [comment]
@tumic0 And the problem exists only with "high resolution" mode.

**Comment by tumic0** [comment]
Most probably it is caused by the HTTP timeout which is 30s at the moment (see the console output). If you try to "harvest" a public server and create a 1200dpi PDF/print you will exceed the limit. I will have a look at the timeout (the downloader part needs some changes anyway) and increase it for PDF exports/printing, but simultaneously I will remove at least the 1200dpi option as:
1. people are evidently trying to use it on public servers
2. such high resolution images are unusable anyway

**Comment by sikmir** [comment]
Yes, that's the reason. But even 600dpi and 300dpi are not fully filled:
- 600dpi: [export1.pdf](https://github.com/tumic0/GPXSee/files/1944716/export1.pdf)
- 300dpi: [export2.pdf](https://github.com/tumic0/GPXSee/files/1944717/export2.pdf)

**Comment by tumic0** [comment]
The connection timeout is now configurable so it may be increased in case of printing/exporting high-dpi maps on slow connections/servers.
