### ISSUE TITLE
Proper units for heart rate and cadence

### ISSUE THREAD

**Issue by sikmir** [tumic0/GPXSee#135]
Now we use **1/min** unit for heart rate, but there's a more proper and widely used one - **BPM** or **bpm** ([beats per minute](https://en.wikipedia.org/wiki/Heart_rate)). What is wrong with 1/min is that the following string:
`Average: 156 1/min | Maximum: 185 1/min`
doesn't look clear enough due to a sequence of number+whitespace+number. Compare with:
`Average: 156 bpm | Maximum: 185 bpm`.
That's much better.
And the same with translations - I've just realized that I'd never write `156 1/мин` in Russian, but I'd rather write `156 уд./мин` or `156 уд/мин`. I think some well-established shortcuts exist in other languages as well.
And the same for cadence: **rpm** ([revolutions per minute](https://en.wikipedia.org/wiki/Revolutions_per_minute)) and **об/мин** (in Russian).

**Comment by tumic0** [comment]
I agree. It turns out to be bad readable. The idea behind it was to use something universal as there is no translation for bpm/rpm in most languages I know. But one can translate it as "U/min" (DE) or "ot/min" (CZ) which is not that nice as bpm/rpm but equivalent "ugly" to 1/min. As soon as I will set up weblate or something similar for the translations (so the strings get not untranslated in languages that do not have an active translator), I will change it.
