### ISSUE TITLE
GPXSee is getting the language for menus wrong (macOS High Sierra 10.13.5)

### ISSUE THREAD

**Issue by HaroldWSchranz** [tumic0/GPXSee#137]
Just downloaded dmg for GPXSee (Mac OS X/GPXSee-5.15.dmg) and running it on my MacBook Pro (under macOS High Sierra 10.13.5) found that GPXSee is getting the language for menus wrong - GPXSee needs to set to the primary language not  one of the other ones (often German or the last one listed); pattern isn't obvious (I often have multiple languages set). I've had to unset all other languages rather than English(Australian). (Fair go mate!). Thanks for any help!

**Comment by tumic0** [comment]
What exact language setting do you have? GPXSee uses the standard QT way of choosing the locale (QLocale::system()), so there is not much I can/will do about the issue. According to available info about how QT chooses the system locale, it is based on the region setting rather than the language setting, so maybe this is the problem in your case.
