### ISSUE TITLE
more graphs visible together

### ISSUE THREAD

**Issue by pvanek** [tumic0/GPXSee#14]
what about to change graphs from QTabWidget to QDockWidget? It can allow me to see more graphs in parallel...

**Comment by JobNoorman** [comment]
What would be very handy then is to have the red selection line synchronized between all graphs. That way it is easy to see, for example, what your heart rate is doing during a steep climb.

**Comment by tumic0** [comment]
The marker IS synchronized across the various graphs. You only can't see multiple graphs at the same time. But if you switch from one graph to another, the marker will stay on the last positon.

**Comment by JobNoorman** [comment]
Aha I somehow never noticed that before. Ignore my previous comment then :-)

**Comment by JobNoorman** [comment]
If anyone is interested, I created a proof on concept implementation using `QDockWidget`s [here](https://github.com/JobNoorman/GPXSee/tree/dockable-graphs). As explained in the [commit](https://github.com/JobNoorman/GPXSee/commit/f064b7e8334f72009c89e00f16812340079e76fc), there are still some issues left::
- The initial layout of the dock widgets seem kind of random. It would be nice to apply some kind of layout to them;
- Most properties of the dock widgets (location, tab status, floating) are remembered when hiding and then showing them. However, if a widget was closed before hiding the graphs, it shows up again when
  showing them;
- The old printing functionality where only the visible graph is printed when not using a separate graph page doesn't work anymore since multiple graphs can now be visible at once.

Note that I only tested it under Linux and you need a C++11 compiler to build.

**Comment by tumic0** [comment]
Nice work. But it only proves what I have been expecting - that it would make GPXSee look & work completely different than it is today. Instead of a small and clean viewer it would become a "complicated" analyzer app, which there are plenty of (QMapShack, Golden Cheatah, ...). So thank you for helping me to close this long standing issue as "won't implement" ;-).

**Comment by JobNoorman** [comment]
I agree: I, too, love the simplicity of GPXSee.

However, did you know `QDockWidget`s can be tabbed? If added to the bottom dock widget area and tabbed by default, it almost looks exactly as the current layout _and_ provides the flexibility of dock widgets. Please see my [commit](https://github.com/JobNoorman/GPXSee/commit/7c7e1c439fe878f06f02dcbbc677618d6a368d9a) on [this branch](https://github.com/JobNoorman/GPXSee/tree/dockable-graphs-tabified) for a proof of concept.

**Comment by tumic0** [comment]
It is not that bad, bud still there are some issues that I don't want to exchange for the questionable benefit of more graphs visible together.
- The redundant 20px (the dock widget frame)
- The poor QT dock widget handling - jerky movement, unpredictable reordering, poor performance...
