### ISSUE TITLE
Provide a Flatpak package for Linux

### ISSUE THREAD

**Issue by thecursedfly** [tumic0/GPXSee#143]
Hi,

As you may have heard, Flatpak packages are a universal method to distribute applications for Linux.
Anybody can download and install the flatpak applications from flatpak.org (or alternative flatpak repositories).
This is a preferred method to distribute user applications, allowing for cross distro compatibility, no dependency hassles, the possibility to use just released versions even on older distributions, possibility to sandbox the application, and more...

Therefore, please provide a Flatpak package for Linux.

The developer documentation can be found here: http://docs.flatpak.org/en/latest/

Thanks

**Comment by tumic0** [comment]
Flatpak packages are definitely not the "preferred method to distribute user applications" on linux. Flatpack is a hack/workaround for non-opensource applications where the authors are not willing/able to prepare standard packages or a workaround for bureaucratic distributions like Debian, where adding a package takes several years.

GPXSee is opensource and with minimal dependencies, so creating a proper package for any sane distribution is almost trivial. Additionally, the latest GPXSee package is provided for 26 linux distributions/versions which should cover most of the "linux world". The remaining users can compile GPXSee from source.

So sorry, but there will be no "official" flatpack package of GPXSee.

**Comment by thecursedfly** [comment]
No need to be grumpy (it surely sounds like that); this is a reasonable request seen the recent popularity that flatpak enjoys, in the face of it's features.

I did not say that it is **the** preferred method to distribute software for Linux, but **a** preferred method, for several reasons. That, because it allows to sandbox the application, allows to avoid dependency problems once and for all, allows to distribute the latest release to several/all distributions in one universal package, automatically supports any new or old distribution release that supports flatpak, just to name a few good reasons.
For these reasons it's not a hack/workaround for non-opensource applications, but brings actual advantages to any application, including opensource.

There would be no need to provide it for those 26 distributions/versions with a flatpak package, but just one (of course those distributions/versions need to support flatpak, but I believe that is easier than requiring the maintenance of thousands of applications instead). Why require tens of people to waste time packaging and testing the same application for every distribution/version when that can be avoided by doing it just once with a flatpak? 
Also stating "the remaining users can compile from source" kinda defeats the purpose of packages at all no? It also requires the users to be more tech savvy than should be required from common users (I wouldn't know where to start for example).

Nice way to greet somebody who appreciates the application and was only trying to help the community by increasing the availability of it.

Anyway, thanks... I guess!

**Comment by tumic0** [comment]
Well, there is a need to be grumpy as I really do not want to support the linux ecosystem becoming so fragmented, that every two applications have a different package manager. I want a single package manager on my linux, not python programs being managed using pip, javascript programs using npm, half of GUI applications using flatpack and the other half using appimage...

Flatpack has its usage for non-opensource applications but for "regular" applications it is "no way" for me (not to mention all the problems with the runtimes and system integration). Additionally, creating another package (flatpack) for every release is an extra work that can be spent more useful on GPXSee developement so all GPXSee users can profit from this work, not only an absolute minority.

Don't take it personally, but as GPXSee is a 100% personal hobby project, there are simply requests that I'm going to ignore even when they are reasonable for some individual/group of people.

**Comment by luv** [comment]
Also note that if you provide a flatpak package, you (as opposed to the distribution) become responsible for monitoring known security vulnerabilities in the dependencies and rebuilding and updating your flatpak package as necessary. That's quite a big future obligation for a hobby project.

**Comment by griga-upjs** [comment]
> 
> Nice way to greet somebody who appreciates the application and was only trying to help the community by increasing the availability of it.
> 

If you want to help community by increasing the availability of application, you can maintain flatpack package yourself (OSS, remember?). You don't help much with making people to do something or talking about it.

**Comment by sikmir** [comment]
> If you want to help community by increasing the availability of application, you can maintain flatpack package yourself (OSS, remember?).

In support of what you said, I just leave it here:

[![Packaging status](https://repology.org/badge/vertical-allrepos/gpxsee.svg)](https://repology.org/metapackage/gpxsee/versions)

**Comment by tumic0** [comment]
Good job! The betting odds for GPXsee being in Debian before running on Amiga or ZX Spectrum have just dropped somewhere to 1.1 : 1 ;-)

**Comment by sikmir** [comment]
@tumic0 What about applying [the patch](haikuports/sci-geosciences/gpxsee/patches/gpxsee-6.0.patchset) to upstream? Qt supports Haiku (see Q_OS_HAIKU in qt5/qtbase/src/corelib/global/qsystemdetection.h).

**Comment by tumic0** [comment]
Looks like you didn't get, who "Pacoš z Bohnic" is... ;-)

**Comment by MarSik** [comment]
I did. Or guessed. However I stand behind my arguments from that other discussion. The desktop application ecosystem has evolved significantly over the last five years.

Even your package version list illustrates the issue. Fedora has 12.3, Arch 13.2, Gentoo 13.1, Manjaro stable 12.4, openSUSE Leap 11.12 and Debian nothing (as we have discussed and joked about).

Users nowadays want a stable OS with the option to switch versions as needed to resolve driver and OS level issues, but at the same time they want the latest and greatest desktop applications. And they do not want to care about library versions or dependencies that prevent having the latest app or about needing administrator rights. Sometimes (probably not the case for GPXSee, but FreeCAD for example) users actually want to have to versions of the same application installed at the same time.

My personal preference is Flatpak as I have explained, because
- it is native in Gnome and supported by Freedesktop
- it runs on all modern distributions (Snap requires AppArmor and disabled SELinux)
- is automatically updated (AppImage does not for most people) and shares Runtimes
- allows 3rd party repositories so no vendor lock-in like Snap effectively used to have)
- Flatpak also sandboxes the application and can restrict access to resources and user data (again as opposed to AppImage). This can be important when you process untrustworthy data. Parsing bugs do happen...

RPMs, DEBs and other binary formats cannot provide this and more and more projects (desktop GUI apps to be exact) are moving to either AppImage or Flatpak. Snap adoption and support seems to be limited compared to the other two.

**Comment by tumic0** [comment]
> I did. Or guessed. However I stand behind my arguments from that other discussion. The desktop application ecosystem has evolved significantly over the last five years.

First of all, the desktop (and Linux desktop especially) is dead and I would not call that an evolution...

>  Even your package version list illustrates the issue. Fedora has 12.3, Arch 13.2, Gentoo 13.1, Manjaro stable 12.4, openSUSE Leap 11.12 and Debian nothing (as we have discussed and joked about).

I do not see an issue here. Distros that have good processes and active community keep up very well with GPXSee developement (there are only 14 days between 13.0 and 13.2). Distros that have releases frozen in time like openSUSE Leap are expected to have older versions. It is your choice what kind of system you like.

> Users nowadays want a stable OS with the option to switch versions as needed to resolve driver and OS level issues, but at the same time they want the latest and greatest desktop applications. And they do not want to care about library versions or dependencies that prevent having the latest app or about needing administrator rights. Sometimes (probably not the case for GPXSee, but FreeCAD for example) users actually want to have two versions of the same application installed at the same time.

I don't think so. Most users do not care how old their SW is as long as it does what they need. The developers (me included) think that every minor change in their SW is super important for the user, but usually it is not. And when you really need a brand new  version, you can always go to GitHub and compile it yourself. Yes, that may be tricky for the Average Joe, but Linux is not a system for the Average Joe and I do not want it to become such, because than we would end up with a copy of Windows (there is nothing bad about Windows but we already have this kind of ecosystem). Which is exactly where all this Flatpack "attempts" are going to end - in a much more closed ecosystem than today ruled by some big corporation. It's not a coincidence that the biggest promoters of such systems are RedHat and Canonical.

A system, where the SW developers are "forced" to create their software compatible with multiple distros makes the SW better as it prevents the mess that you can today see in the JavaScript world or amongst (corporate) Windows software. It also produces innovative distros like Arch linux or NixOS instead of something like Android.

> My personal preference is Flatpak as I have explained

I have no problem with your preference as long as you do not force others to see it the same way. You love Flatpack? Then build yourself a Flatpack package. GPXSee is opensource and creating the Flatpack is easy-peasy according to all the Flatpack evangelists...

> RPMs, DEBs and other binary formats cannot provide this and more and more projects (desktop GUI apps to be exact) are moving to either AppImage or Flatpak.

Don't confuse RPM/DEB with RedHat/Debian. It is the distros, that are not capable not the binary formats. RHEL/Debian is definitely not suitable for a modern desktop (which is dead anyway...), but there is much more in the Linux world than Debian/RHEL.

**Comment by MarSik** [comment]
I am not going to ask you maintain the build yourself, but I think you are too pessimistic about linux desktop and the recent development. And you obviously have some very inaccurate information (and bias against corporations :)

> Which is exactly where all this Flatpack "attempts" are going to end - in a much more closed ecosystem than today 
> It's not a coincidence that the biggest promoters of such systems are RedHat and Canonical.

Flatpak is actually a Freedesktop project. And natively supports 3rd party repos, anyone can setup one. So no vendor lock-in (Freedesktop itself belongs to the X.org foundation)

Flathub is also not directly related to RH or Canonical in any way. It is backed by Freedesktop and CNCF (again, a foundation with a long list of very diverse members).

> RHEL/Debian is definitely not suitable for a modern desktop (which is dead anyway...),

So think about Fedora, or Fedora Silverblue (no RPMs, ostree based). Flatpak is the prefered way to install user applications there.

Speaking about NixOS: The docs and https://matthewrhone.dev/nixos-package-guide also mention Flatpak

And so do Arch and Manjaro in their docs.

> Most users do not care how old their SW is as long as it does what they need.

Strictly speaking you are right, but...

This commonly maps to demanding the latest features possible. Not all users use all the features of course, but think about your user base. GPXSee is a tool that will be predominantly used by technically savy users and those often do adopt features quickly.


> GPXSee is opensource and creating the Flatpak is easy-peasy according to all the Flatpak evangelists...

It could be easier, but it depends on the amount of dependencies the app has. GPXSee will probably not be that hard.

But of course, scratch your own itch and all that. So whoever is interested should do the packaging work.

This should be an issue tracker and not a discussion so I apologize for the polemic. I was a bit annoyed by the grumpiness and the inaccuracies in your perception of modern approaches to packaging desktop apps.

**Comment by crse** [comment]
Any reconsideration for Flatpak?

Linux is continuing to grow, and Flatpak via Flathub are the one of most common distribution.
On Steam alone, it recently reach 10% of English Steam users (data via [GamingOnLinux](https://www.gamingonlinux.com/steam-tracker/)). Other data metrics also show similar trend.
<img width="968" height="587" alt="Image" src="https://github.com/user-attachments/assets/837b3ca3-4fa7-4e7d-b7d9-dccb04aef370" />

Flathub itself regularly showcase interesting software. On the [trending section](https://flathub.org/en/apps/collection/trending/1) alone, there are so many niche software being discovered. This also could be a good way to get more contributor and community members.

**Comment by tumic0** [comment]
> Any reconsideration for Flatpak?

No, nothing significant has changed in the last decade. The problems with the integration and the runtimes are still there and so is my faith in a single package manager on a Linux system.

> Flatpak via Flathub are the most common distribution

Source? I really doubt that there are overall more Flatpak packags installations than native packages installations...

> Flathub itself regularly showcase interesting software. On the [trending section](https://flathub.org/en/apps/collection/trending/1) alone, there are so many niche software being discovered. This also could be a good way to get more contributor and community members.

Most of the projects on that list were slop even before AI. I would even say that appearing there brings a serious project more harm than benefits...

**Comment by crse** [comment]
Immutable distro won't have access to any other packaging other than Flatpak.
SteamOS, Bazzite, Fedora Silverblue, Aurora, KDE Linux, Gnome OS, and so on...

> Most of the projects on that list were slop even before AI. I would even say that appearing there brings a serious project more harm than benefits...

Most of them are new software, and only one of them are merely using AI generated logo.
It's good that people wiling to check newer software even if it's still rough edges.

[Popular apps section](https://flathub.org/en/apps/collection/popular/1) showed that people are actually using Flathub.
Example for relatively niche software:
- [a disk images writer](https://flathub.org/en/apps/io.gitlab.adhami3310.Impression) with 700 thousands downloads.
- [video transcoding tool](https://flathub.org/en/apps/fr.handbrake.ghb) with 1.1 millions downloads.
- [music tagger](https://flathub.org/en/apps/org.musicbrainz.Picard) with 140 thousands download.

**Comment by tumic0** [comment]
> Immutable distro won't have access to any other packaging other than Flatpak.
SteamOS, Bazzite, Fedora Silverblue, Aurora, KDE Linux, Gnome OS, and so on...

So what? Hannah Montana Linux users also have no "single click/command" access to GPXSee... In the Linux world I like, it's the distributions job to provide the SW to it's users, not the SW authors. SW authors provide the source codes. Having yet another OS where the apps come with all their dependencies (even though grouped to runtimes) from a "store" makes no sense for me, we already have Windows and macOS.

> Most of them are new software, and only one of them are merely using AI generated logo.

My answer was about the "slop" part (["digital content that is perceived as lacking in effort, quality, or meaning"](https://en.wikipedia.org/wiki/AI_slop)) of AI slop, not the "AI" part. Like the "disk images writer" which is nothing more than a fancy `dd` command.

> [Popular apps section](https://flathub.org/en/apps/collection/popular/1) showed that people are actually using Flathub.
> Example for relatively niche software

Yes, there may be good software on that list as well, but it's like looking for a needle in a haystack. Handbrake is decades old (a decade older than Flatpak itself...) it really does not matter if it is listed in a Flatpak "trending" list or even if it is on Flathub at all. And the same applies to GPXSee which is also long past the point where being listed in such a list may matter. People who are looking for something like GPXSee can find it much more easily using Google (or ChatGPT) than to rummage through the garbage of all the slop Flatpak apps.

**Comment by joklaps** [comment]
Hello @tumic0 . I landed on this GitHub issue, reading it I see you said here https://github.com/tumic0/GPXSee/issues/143#issuecomment-1552185910 that you don't object others building a Flatpak package. I'll give it a try and see if I can get it submitted to FlatHub. I'll build it from the release tar bundle for the current release 16.11

**Comment by tumic0** [comment]
Building a Flatpak package for yourself and distribute it on FlatHub are two completely different things. While I have no objections against the first, in the second case I really would like that there is clearly stated on FlatHub that this package is not "official" and people should not come here for any support.

**Comment by hfiguiere** [comment]
Do you prefer somebody comes with a bug that was fixed 6 years ago because they use a 4 year old distro that never update application packages?

This is one of the key reasons Flatpak exist: allowing users to install application that are kept up to date.

Right now I'm the only (flathub admin) supportive of not closing (rejecting) the submission, but the other mod find your stance too extreme for them to want to bother, regardless of anything else.

**Comment by tumic0** [comment]
> Do you prefer somebody comes with a bug that was fixed 6 years ago because they use a 4 year old distro that never update application packages?

Yes, I definitely prefer someone with an old GPXSee version over someone with a version that is broken by design (Flatpak) as the old version can always be upgraded while the issues with Flatpak are permanent. Requiring the users reporting bugs to use the latest program version is something that most opensource projects do, so I don't see a reason why GPXSee should be an exception.

> This is one of the key reasons Flatpak exist: allowing users to install application that are kept up to date.

That may be true, but Flatpaks are definitely not the only way how to have up-to-date applications so I see no reason why it should be handled any special.

> Right now I'm the only (flathub admin) supportive of not closing (rejecting) the submission, but the other mod find your stance too extreme for them to want to bother, regardless of anything else.

Well, it does not make much sense to threaten someone that there will be no Flatpak when this is exactly what he wants...

**Comment by hfiguiere** [comment]
I don't see how it is handled special either. The only thing expected here is  that you not be downward hostile to it. 

The few minor changes to the appstream file (which is 1. not flatpak specific 2. would benefit distro packages as well 3. boils down from validating the file with the appstream tooling, which most distro don't, and which is not under our control either.) are not even blocking. It's always nicer when upstream accept them, **but it can still be dealt without your involvement**.

**Comment by tumic0** [comment]
> I don't see how it is handled special either. The only thing expected here is that you not be downward hostile to it.

You simply cannot expect SW authors to be positive towards someone crippling their application and causing harm to its reputation.

> The few minor changes to the appstream file (which is 1. not flatpak specific 2. would benefit distro packages as well 3. boils down from validating the file with the appstream tooling, which most distro don't, and which is not under our control either.)

Have you looked at the proposed [changes](https://github.com/joklaps/flathub/blob/abfbfbb246fa8385bd99be33916b8df6cfd3c649/gpxsee-appdata.patch) at all? There is a `id` change which is explicitly prohibited by the appstream documentation for consistency, there are all `mimetype` entries removed, the `categories` are completely changed, ... Those are not minor changes and they would break other distros! And the XML file validates fine and many distros [validate](https://src.fedoraproject.org/rpms/gpxsee/blob/rawhide/f/gpxsee.spec#_49) it on every package build.

**Comment by barthalion** [comment]
>Those are not minor changes and they would break other distros! And the XML file validates fine and many distros [validate](https://src.fedoraproject.org/rpms/gpxsee/blob/rawhide/f/gpxsee.spec#_49) it on every package build.

Using a deprecated tool with a relaxed ruleset… They may as well not validate it at all.

**Comment by tumic0** [comment]
The relaxed ruleset means that the style (e.g. line lengths) is not checked which is something that does not belong into any formal validation and is thus not used by any sane distribution. Yes, there is `appstreamcli` nowdays, but that does not mean `appstream-util` is useless. From the compatibility point-of-view `appstream-util` is much better (GPXSee is expected to be build and it's appstream XML file be validated on several years old systems) and it is still the preferred tool in many distributions like [Fedora](https://docs.fedoraproject.org/en-US/packaging-guidelines/AppData/).

But the Flatpak people (you) evidently know better and even go to show their professionalism to the projects by telling fairy tails that using a proved and compatible tool for validation equals no validation at all...

**Comment by barthalion** [comment]
We've spent years maintaining appstream-glib. But the GPXSee people (you) evidently know better, a real professional! Have a nice weekend.

**Comment by tumic0** [comment]
Yes, the GPXSee people (me) know better what fits best for GPXSee. And the same applies to Fedora and the Fedora people. Your three lines of code in appstream-glib simply do not qualify you to understand the needs of other projects better than their authors, live with that.
