### ISSUE TITLE
map and graphs marks are not two-way synchronzied

### ISSUE THREAD

**Issue by pvanek** [tumic0/GPXSee#15]
when I click into grap, the red mark is created in the graph itself and in the map (I'd like to see it bigger ;)) - that's good.

But I'd expect to move the map mark and its graph representation moved when I click into the blue line in the map. Also maybe it can scroll in the map and graph on mouse move over the line (like eg. maps.cz do it)

**Comment by tumic0** [comment]
The problem is, this can not work wery well with multiple tracks - there would have to be a weird logic that would also move the other markers. Additionally, I personally do not find it much usable to move the path marker around the map, at least not that usable to bother with the implementation of such feature ;-)
