### ISSUE TITLE
Great circle through the pair of antipodal points

### ISSUE THREAD

**Issue by sikmir** [tumic0/GPXSee#155]
Something goes wrong after 9957e1834eab5a8586766854b9b64ade7b42df6c.

### Steps to reproduce
1. Create some track connecting two [antipodes](https://en.wikipedia.org/wiki/Antipodes) (45°N 8°E and 45°S 172°W):
```shell
$ cat << EOF > antipode.gpx
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<gpx xmlns="http://www.topografix.com/GPX/1/1".
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     version="1.1"
     creator="test"
     xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
 <trk>
  <name>antipode</name>
  <trkseg>
   <trkpt lat="45" lon="8"></trkpt>
   <trkpt lat="-45" lon="-172"></trkpt>
  </trkseg>
 </trk>
</gpx>
EOF
```
2. Open with GPXSee:
```shell
$ gpxsee antipode.gpx
```
### Actual behaviour
GPXSee 5.17.r1115.2501f834 ([orthodrome](https://en.wikipedia.org/wiki/Great_circle)):

![screenshot2](https://user-images.githubusercontent.com/688044/45487734-e669ad80-b767-11e8-971d-445084850c6b.png)

Let's move the 2nd point a bit to 45°S 171°W:

![screenshot3](https://user-images.githubusercontent.com/688044/45488731-ecad5900-b76a-11e8-9fc8-7b9b3ebe4cda.png)

That's OK.

### Expected (previous) behaviour
GPXSee 5.17 ([loxodrome](https://en.wikipedia.org/wiki/Rhumb_line)):

![screenshot1](https://user-images.githubusercontent.com/688044/45487741-eb2e6180-b767-11e8-8031-896de5fd10ae.png)

### RCA

[Great circle](https://en.wikipedia.org/wiki/Great_circle):
> For most pairs of points on the surface of a sphere, there is a unique great circle through the two points. The exception is a pair of antipodal points, for which there are infinitely many great circles.

**Comment by sikmir** [comment]
Another one broken edge case:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<gpx xmlns="http://www.topografix.com/GPX/1/1"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     version="1.1"
     creator="test"
     xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
 <trk>
  <name>60 parallel</name>
  <trkseg>
   <trkpt lat="60.000000" lon="-180.000000"></trkpt>
   <trkpt lat="60.000000" lon="0.000000"></trkpt>
   <trkpt lat="60.000000" lon="179.999999"></trkpt>
  </trkseg>
 </trk>
</gpx>
```
GPXSee 5.17:

![screenshot1](https://user-images.githubusercontent.com/688044/45489869-42373500-b76e-11e8-8891-78839c1791a6.png)

GPXSee 5.17.r1115.2501f834:

![screenshot2](https://user-images.githubusercontent.com/688044/45489870-42373500-b76e-11e8-9afb-71dc463a3395.png)

**Comment by sikmir** [comment]
By the way:
```shell
$ curl -s http://www.topografix.com/GPX/1/1/gpx.xsd | sed -n '737,747p'
  <xsd:simpleType name="longitudeType">
	 <xsd:annotation>
	  <xsd:documentation>
		The longitude of the point.  Decimal degrees, WGS84 datum.
	  </xsd:documentation>
	 </xsd:annotation>
    <xsd:restriction base="xsd:decimal">
      <xsd:minInclusive value="-180.0"/>
      <xsd:maxExclusive value="180.0"/>
    </xsd:restriction>
  </xsd:simpleType>
```
That means 180.0 is invalid value for longitude.
But GPXSee accepts it:
https://github.com/tumic0/GPXSee/blob/df104b16c62dc05e8d8a28e490919f2d776d8033/src/data/gpxparser.cpp#L37-L40

I don't know, there may be some reason behind that. At least many other programs accept 180.0 as well.

**Comment by tumic0** [comment]
Yes this corner cases are not handled at the moment, but I doubt, that on real data someone will trigger them. The problem is, the limitations are principal, i.e. the math/physics is the limiting factor here:

1. The first issue is clear - there are infinity shortest paths between antipodes.
2. If the path goes directly over a pole, the latitude goes to infinity. This is a property of the Mercator projection (other map projections have similar limits) and is why you never have the poles on maps With Mercator projections. The tiles on OSM/Google maps are for example limited to ~85 degrees of latitude.

However generally, this is a better way how to display the paths as:
1. It shows the correct path corresponding to the computed distance. GPXSee, like most other tools, uses the Haversine formula for computing path lengths. Rhumb lines are much longer in case of transcontinental paths.
2. Some real cases like the following GPX
```
<?xml version="1.0" encoding="utf-8"?>
<gpx creator="mapy.cz" version="1.1" xmlns="http://www.topografix.com/GPX/1/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
    <trk>
        <name></name>
        <trkseg>
            <trkpt lat="34.0531539917" lon="-118.202325404">
                <ele>119.180919313</ele>
                <name>Los Angeles</name>
            </trkpt>
            <trkpt lat="-33.9064002782" lon="151.226385534">
                <ele>32.6621818702</ele>
                <name>Sydney</name>
            </trkpt>
        </trkseg>
    </trk>
</gpx>
```
were displayed completely wrong, going over the longer part of the globe. Also "local paths" crossing the date line should work now.

I may take a look on some workarounds for the corner cases, but as "real data" will hardly trigger them, I don't think that this is a big issue. After all, GPXSee is not the control logic of a nuclear missile ;-)

**Comment by tumic0** [comment]
Btw., there is technically only one issue - the one with the antipodes. The vertical lines are in fact a correct representation of the path (in Mercator projection).
