### ISSUE TITLE
French language by default?

### ISSUE THREAD

**Issue by Bzzliteyr** [tumic0/GPXSee#157]
I just found and downloaded your program, I love it! Though I am bilingual and can understand, I would rather have my app in English. Can you talk me through getting or changing to an English version?

**Comment by sikmir** [comment]
Just set proper LANG variable, something like this:
```fish
$ set LANG en_US.UTF-8
$ gpxsee
```

**Comment by Bzzliteyr** [comment]
Can you talk me through doing that on a Mac? I feel I'm not saavy enough to try on my own.

**Comment by tumic0** [comment]
I suppose you have both (fr, en) languages in your preferences, but English selected as the first choice. In the last released version (and all previous), there is a "bug" (missing English translation file)  that causes the French language to be selected by default. This will be fixed in the next version (already in GIT master). Til then, you can fix it by manually copying the attached English translation file to the remaining translation files in /Applications/GPXSee.app/Contents/Resources/translations.

[translations.zip](https://github.com/tumic0/GPXSee/files/2403087/translations.zip)

**Comment by tumic0** [comment]
> sikmir
Setting the environment variable does not work on Mac, Qt takes the language always from the languages list configured in the preferences.

**Comment by sikmir** [comment]
Sure, I've just kept Linux in mind.

**Comment by Bzzliteyr** [comment]
Adding the translation file in Mac did not work, gave me a "damaged file" error.
