### ISSUE TITLE
[feature] Load geotagged images and show thumbnails along the track

### ISSUE THREAD

**Issue by marsark** [tumic0/GPXSee#168]
I propose following new feature for the GPXSee.

1. load image files (mainly jpegs from cameras) with geotagging attributes from the directory and display their thumbnail along the recorded track. Click on the thumbnail displays a big preview of the image.
2. add geotagging attributes and save them to the images captured with cameras without GPS module based on the correlation between image capture timestamp and track log timestamp.

**Comment by robvelez** [comment]
+1 on this feature request! I use Strava and they implement this nicely.

**Comment by tumic0** [comment]
Adding support for geo-tagged images sounds reasonable. The question is, how to display the images. I would prefer a simple point/icon and a thumbnail in the tool tip (which would be permanent like requested in #142). Another question is, how the "full size" image should be displayed. Here I would prefer opening the system's image viewer rather than trying to show the image in GPXSee.

When 7.0 is out, I will look at it and see how much work is necessary to implement this.

**Comment by marsark** [comment]
Great! I think that a combination of the item list (displayed somewhere on the left or right side of the map) of loaded files and img-like icons along the track with thumbnail in tooltip will be the best. You can implement full-size viewer as a configuration option which could override system default.

**Comment by tumic0** [comment]
Implemented in 541e6587418f6e6f76ca2f339714607d64e5db42.
