### ISSUE TITLE
FR: Polar Stereographic (EPSG:9829) coordinate transformation support

### ISSUE THREAD

**Issue by sikmir** [tumic0/GPXSee#181]
### Steps to reproduce
```bash
$ mkdir -p ~/.local/share/gpxsee/csv
$ cat /usr/share/gpxsee/csv/pcs.csv | sed '862iWGS 84 / Antarctic Polar Stereographic,3031,4326,19992,9001,9829,4490,8806,0,9001,8807,0,9001,8832,-71,9102,8833,0,9102,,,,,,,,,' > ~/.local/share/gpxsee/csv/pcs.csv
$ cat << EOF > ~/.local/share/gpxsee/maps/LIMA.xml
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://www.gpxsee.org/map/1.3" type="WMS">
  <name>LIMA</name>
  <url>https://limaims.cr.usgs.gov/arcgis/services/Antarctica/USGS_EROS_Antarctica_Reference/MapServer/WmsServer</url>
  <copyright>Map data: U.S. Geological Survey (USGS), British Antarctic Survey (BAS), National Aeronautics and Space Administration (NASA)</copyright>
  <layer>LIMA_Full_1km</layer>
  <crs>EPSG:3031</crs>
</map>
EOF
$ crudini --set ~/.config/gpxsee/gpxsee.conf Map map LIMA
$ gpxsee
```
### Actual behaviour
```bash
/home/sikmir/.local/share/gpxsee/csv/pcs.csv:862: Unknown coordinate transformation code
/home/sikmir/.local/share/gpxsee/maps/LIMA.xml: EPSG:3031: unknown CRS
```
### Links
- [EPSG:9829 (Polar Stereographic)](https://epsg.io/9829-method)
- [EPSG:3031 (WGS 84 / Antarctic Polar Stereographic)](https://epsg.io/3031)
- [Landsat Image Mosaic Of Antarctica (LIMA)](https://lima.usgs.gov)
  - [Locate Online GIS Resources for Antarctica](https://lima.usgs.gov/locate.php)
- [USGS Antarctic Research Atlas](https://lima.usgs.gov/antarctic_research_atlas/)
- [Antarctica in OpenStreetMap](https://blog.jochentopf.com/2013-02-04-antarctica-in-openstreetmap.html)
- [Track example](https://www.wikiloc.com/snowshoeing-trails/kaptan-scottin-guney-kutup-rotasi-15825619)

**Comment by sikmir** [comment]
Cool! Thanks!

**Comment by sikmir** [comment]
@tumic0 It looks like something wrong with track-centering:
```bash
$ gpxsee scott.gpx
```
![scr1](https://user-images.githubusercontent.com/688044/50864343-cadb8000-13b2-11e9-9608-400f492041bc.jpg)

**Comment by tumic0** [comment]
The problem is in the track bounding rect, which spans over the anti-meridian. GPXSee always assumes the maximal bounding box (which is wrong in this case). This has not only historical reasons, but also some practical reasons. For example on the most common (Web)Mercator maps, you see the whole track even thought the map does not wrap. I could theoretical use some kind of origin-aware bounding boxes which would contain the info if the minimal or the maximal bounding rectangle shall be used, but this turned out to be a quiet complex change. So more probably I will keep this in my mind as a "known issue" for now as it only affects some unusual data (Antarctica).
