### ISSUE TITLE
Offset for elevation graph

### ISSUE THREAD

**Issue by yeti01** [tumic0/GPXSee#182]
Devices that work with an altimeter based on atmospheric pressure need a calibration offset to show the correct absolute altitude.
It would be nice to have a feature in GPXSee that adds an offset to the recorded data. If possible it would be even nicer to save the manipulated data back to the file.

**Comment by tumic0** [comment]
Can you please attach an example of such a GPS log file?

**Comment by yeti01** [comment]
Take a look at the example below. In reality I was at 100m height but my device showed 220m. This is because the device determines the height by atmospheric pressure. At that time it was about 998hPa.

**Comment by yeti01** [comment]
![image](https://user-images.githubusercontent.com/1257505/51163538-5dd85680-189a-11e9-9faa-e77c34c13797.png)

**Comment by yeti01** [comment]
My idea is to give the elevation graph manually an offset of -120m after reading the file. Then display the graph with this offset and save the file with the adjusted data.

**Comment by yeti01** [comment]
[2018-12-21-17-40-00.fit.zip](https://github.com/tumic0/GPXSee/files/2758331/2018-12-21-17-40-00.fit.zip)

**Comment by sikmir** [comment]
That is really typical GPS log post-processing task and should be done by other tools.

**Comment by tumic0** [comment]
I agree. This is something that a post processing tool should do. Implement it in a viewer does not make much sense (GPXSee does not rewrite the log files and that won't probably never change). Additionally, GPXSee now (since version 7.2) supports elevation data gathered from DEM files, so if someone has a device that uses/prefers barometric altitudes and those are often dis-calibrated he can always download the DEM data for his region and start using the DEM data.
