### ISSUE TITLE
Enhancement request: "round-robin" server requests.

### ISSUE THREAD

**Issue by JuttaAnders** [tumic0/GPXSee#195]
Would it be possible to use square brackets [] (or something like that) to indicate that gpxsee should "cycle through" the characters within, resulting in round-robin server requests?

`<url>http://oatile[1234].mqcdn.com/tiles/1.0.0/sat/$z/$x/$y.jpg</url>`

**Comment by tumic0** [comment]
With HTTP/2 (supported by GPXSee since  5.16) being the main transport protocol these days this does not make much sense (in fact it is even contra productive). And there won't be many services that support domain sharding and do not support HTTP/2.

Additionally this would make the map definitions backward-incompatible so such definitions would for example not be allowed in the GPXSee-maps repository.

**Comment by JuttaAnders** [comment]
@tumic0 thanks for the explanation.
