### ISSUE TITLE
FR: DEM in GeoTIFF format

### ISSUE THREAD

**Issue by sikmir** [tumic0/GPXSee#213]
Some DEM sources in GeoTIFF format:
* [Copernicus Land Monitoring Service - EU-DEM](https://land.copernicus.eu/imagery-in-situ/eu-dem/eu-dem-v1.1?tab=download)
* [MERIT DEM: Multi-Error-Removed Improved-Terrain DEM](http://hydro.iis.u-tokyo.ac.jp/~yamadai/MERIT_DEM/index.html)
* [Digitales Geländemodell (DGM) Österreich](https://www.data.gv.at/katalog/dataset/d88a1246-9684-480b-a480-ff63286b35b7)

**Comment by tumic0** [comment]
The problem with the TIFF DEM files is, their TIFF format is mostly not supported (e.g. it is BigTIFF) by the standard libtiff that Qt uses in its TIFF image plugin. And I really don't want to write a new image plugin (maybe even a new tifflib) because of such a marginal use case... So lets let this to the GIS tools using GDAL.
