### ISSUE TITLE
Feature-Request Zoom in plot and show more than one graph in a single plot

### ISSUE THREAD

**Issue by WIsbrecht** [tumic0/GPXSee#215]
Hey,

I often find myself wanting to zoom in the data plots. 
It'd be great if one could zoom in the plot by pressing shift for zoom in abscissa direction and ctrl for zoom in ordinate direction respectively plus scrolling with the middle mouse button.
Or simply by selecting a section in the plot.

For a better overview I'd like to see more than one graph in a single plot window by either plotting several datasets in a single plot area or by stacking several plot areas on top of another.

**Comment by tumic0** [comment]
More graphs were already discussed in #14.

Zoomable graphs are a somehow similar story. GPXSee is not designed as a full featured analysis tool with all the data-woodoo like for example GoldenCheatah. Moreover, you can always enlarge the graph using the split slider. That's why a graph zoom has a very low priority. From my personal use of the graph data, I would even say it is not worth the effort to implement it.

**Comment by tumic0** [comment]
Btw., normally I would probably let the zoom graph issue open but as it is bundled with another, already closed issue (= two bad habits at once), the fate was sealed.

**Comment by sikmir** [comment]
> Moreover, you can always enlarge the graph using the split slider.

Out of curiosity, what do you mean here? How is it possible to "enlarge the graph using the split slider"?

**Comment by tumic0** [comment]
I mean the slider that changes the ratio of the map view/graph view.

**Comment by sikmir** [comment]
Aha, I see) I just thought about some horizontal enlargement.

**Comment by tumic0** [comment]
That's also possible. Using a bigger monitor ;-)
