### ISSUE TITLE
Modify speed scale

### ISSUE THREAD

**Issue by scls19fr** [tumic0/GPXSee#225]
Hello,

For some tracks, calculated speed data is a bit noisy

![Capture d’écran 2019-08-22 à 17 20 09](https://user-images.githubusercontent.com/109167/63527350-39fc8380-c501-11e9-8b7e-cd2fb78ef1b5.png)

[Data cleansing](https://en.wikipedia.org/wiki/Data_cleansing) (especially identifying and fixing outliers) could be considered but this is a quite hard task to achieve.

A simpler one could be to simply allow users to be able to set speed scale (min speed and max speed) to plot speed data in a convenient scale.

Kind regards

**Comment by tumic0** [comment]
There already is outlier elimination in GPXSee, check that you have it enabled. But even when enabled, it is not all-powerful. In case you have outlier elimination enabled and it didn't "catch the spike", please provide the input file so I can analyze it.

**Comment by scls19fr** [comment]
Sorry @tumic0 but I don't see where I can see if outlier elimination is enabled or not

**Comment by tumic0** [comment]
In the Options under Data->Filtering

**Comment by scls19fr** [comment]
thanks but it doesn't help much.
Being able to change plot scale is probably the simplest approach.

**Comment by tumic0** [comment]
Well the algorithm is designed to especialy handle the typical "scattered" GPS data. If you have a chunk of data that is all invalid, it will not work very well. It is however very rare to get such speed data when the speed is computed from distance/time (unlike the device reported speeds where this can be observed quiet often), that's why there is a switch for the speed source in GPXSee.

Fiddling with the graph scale is definitely not the right way how to handle outliers. This must be solved by improving the outlier detection, but without the data there is not much I can do about it...

**Comment by scls19fr** [comment]
Data can be downloaded at http://www.netcoupe.net/Download/DownloadIGC.aspx?FileID=34661 (not my flight)

**Comment by tumic0** [comment]
Please attach the file to this issue as

1. It is not accessible without registration
2. It may not be accessible in the feature

**Comment by scls19fr** [comment]
Github doesn't support .igc files as attachment

uploaded to
https://quickfileshare.org/Z90/NetCoupe2019_28597.igc

**Comment by tumic0** [comment]
[NetCoupe2019_28597.igc.gz](https://github.com/tumic0/GPXSee/files/3533065/NetCoupe2019_28597.igc.gz)

**Comment by tumic0** [comment]
Fixed by only using valid IGC B records (ae64ef9d83b4a4166f6a45830030a891268e7e29)
