### ISSUE TITLE
(Small) Error in gpx track display

### ISSUE THREAD

**Issue by devbrand** [tumic0/GPXSee#229]
Hi!

I've been using GPXSee quite a lot recently (with great pleasure!) but now I just stumbled upon what seems to be a bug. To my surprise, the display of the attached track is erroneous in a brief section of the track. It seems that approx. 6 trackpoints (marked in the screenshot of RouteConverter) are disregarded. See the attached screenshots for a comparison of the relevant part. I've loaded the track into additional tools and they all display this part correctly (the track follows the road).

Thanks for taking a look at this problem! And many thanks for providing your great tool!!!

Best regards

[issue.zip](https://github.com/tumic0/GPXSee/files/3559907/issue.zip)

**Comment by tumic0** [comment]
I won't have access to a computer until the end of the weekend, but I'm pretty sure the cause is the outlier elimination algorithm. If you disable outlier elimination in the settings, you should get the expected path.

I will further investigate the data later, but what is strange on the first sight is that the path is a track (with timestamps) not a route but all trackpoints follow exactly the way on the map... This indicates that the file has been generated rather than logged so it is quiet strange why the generation algorithm triggers the statistical outlier treshold (the outlier detection is based on acceleration).

**Comment by devbrand** [comment]
Indeed the expected path is shown when outlier elimination is disabled.

Yes, this gpx file is the result of planning a route with komoot.de. It's not a recorded track.

**Comment by tumic0** [comment]
![acceleration](https://user-images.githubusercontent.com/11480505/64076144-55198100-ccc1-11e9-9f9c-ac4835655ada.png)
I have no idea how komoot.de generates the times in the GPX file, but they are quiet weird - the resulting acceleration would in a "real" track log definitely indicate some GPS signal problems, so from my point of view the outlier detection algorithm works fine here.

You may however consider reporting a bug to komoot.de.
