### ISSUE TITLE
[request] make tile cache folder and offline maps folder selectable in the options

### ISSUE THREAD

**Issue by halftux** [tumic0/GPXSee#23]
I think it would be nice if you could choose the location of tile cache and offline maps.
So that not everything get saved in the profile.

**Comment by tumic0** [comment]
Adding the map file/map directory paths to the settings could be a useful feature as it would allow the users using some "shared" maps without the need of doing symlinks. But I do not see much sense in letting the user to configure the internal cache storage of the application. You can hardly share this data among users (what would be the access rights logic?) and it is not something users are used to configure (did you ever configured your browser's cache location? I doubt it...)

**Comment by tumic0** [comment]
I have decided to close this issue as "won't do". Since the creation of the issue the configuration/data storage of GPXSee has been split to system/user and both can be "redirected" to an arbitrary location by using symlinks. So generally it is possible to have the offline maps wherever one wishes to have it, although the setup is not that user-friendly. But for such a corner-case option this is IMHO enough...

**Comment by igorpupkinable** [comment]
I've just relocated `~/.local/share/gpxsee/` and `~/.cache/gpxsee/` to unencrypted portion of the disk and linked back with symlinks. Everything works just fine. Thanks.
