### ISSUE TITLE
Erro when opening an image with GPS coordinates

### ISSUE THREAD

**Issue by JVillafruela** [tumic0/GPXSee#260]
When opening a [photo ](https://framapic.org/jHUD6KQhS4HE/NML79h51x4Op.jpg) taken with my smartphone (Nokia 7 plus) I have the error "Invalid/missing GPS coordinates", however this photo is correctly geolocated in other software  ([eg. JOSM](https://josm.openstreetmap.de/), [Geosetter](https://geosetter.de/en/main-en/)).

Exiftool shows the gps tags : 
```bash
exiftool   -gps:all  IMG_20190409_161913.jpg
GPS Latitude Ref                : North
GPS Longitude Ref               : East
GPS Altitude                    : 275 m
GPS Time Stamp                  : 14:19:13
GPS Date Stamp                  : 2019:04:09
```

**Comment by tumic0** [comment]
The image really has an invalid GPS EXIF. The GPSLatitude/GPSLongitude tags use the SRATIONAL (10) data type instead of the correct RATIONAL (5) as described in the specification (SRATIONAL makes no sense here as the GPS entry must also contain the GPSLatitudeRef/GPSLongitudeRef tags).  The reason why it works in some other SW is, that this SW is not that strict when parsing the data or it already has some workarounds for images produced by HMD Global phones.

I will probably add an workaround for such broken images, but it would be nice to have samples from the S or W hemispheres to see how exactly have the Chinese broken in.
