### ISSUE TITLE
Track not being drawn through points.

### ISSUE THREAD

**Issue by dpawlyk** [tumic0/GPXSee#288]
In the latest version, the track is not being drawn through points near the following. This happens with the FIT and TCX versions of the same RWGPS route.
![image](https://user-images.githubusercontent.com/26445864/80869074-3f9f9100-8c6c-11ea-87b6-b48a410ccae8.png)

```
           <LatitudeDegrees>41.60644</LatitudeDegrees>
            <LongitudeDegrees>-73.92108</LongitudeDegrees>

```
That's also a course point in the file at that location.

```
     <CoursePoint>
        <Name>West Main </Name>
        <Time>2020-05-02T19:58:22Z</Time>
        <Position>
          <LatitudeDegrees>41.60644</LatitudeDegrees>
          <LongitudeDegrees>-73.92108</LongitudeDegrees>
        </Position>
        <PointType>Straight</PointType>
        <Notes>Continue onto West Main Street, NY 9D</Notes>
      </CoursePoint>

```

Here's a link to the TCX file.

https://www.dropbox.com/s/a8hhuz01d0kzckj/R31232979.tcx?dl=0

**Comment by tumic0** [comment]
That's caused by the outlier elimination. If you disable it, you will get the "expected" path.

I have really changed the outlier detection threshold recently which seemed to be a marginal change (not even worth mentioning in the changelog), but it turns out it was not that innocent... As I have seen more tracks being "cut of" with this threshold, I have reverted it for the next release in 571ed087e33637fc3daeb16e1f610df31e788099.
