### ISSUE TITLE
POI issues

### ISSUE THREAD

**Issue by tomthecat** [tumic0/GPXSee#29]
I still experience problems with POIs. In my understanding, POIs could be routes as well, not only points.

Try these both routes:

www.skitourenguru.ch/calc_data/Routes/Switzerland_NoExt.gpx
www.skitourenguru.ch/calc_data/kml/Switzerland_Corridors.kml

In the fist case, routes should be shown as POIs. In the latter case, 2D corridors should be overlayed.

Thank you for considering implementation.

**Comment by tumic0** [comment]
> In my understanding, POIs could be routes as well, not only points.
At the moment only waypoints are used as POIs when a "POI file" is loaded.

Using routes as POIs could most probably also be implemented, I just newer had the idea/need. I will have a look at it.

**Comment by tumic0** [comment]
Just a remark regarding the "Corridors" KML file. The file defines "polygons" which are unlike paths/routes 2D objects. There is no support in GPXSee for displaying such objects (even as data files). This is because GPXSee is designed/intended as a GPS log file viewer, not a full featured GIS. If you need such advanced functionality, you have to use some real GIS software to do so.

**Comment by tomthecat** [comment]
> If you need such advanced functionality, you have to use some real GIS software to do so.

KDE Marble, for example ;-)
