### ISSUE TITLE
Eliminate GPS outliers removes most of the data in a very large data set

### ISSUE THREAD

**Issue by Rock2far** [tumic0/GPXSee#297]
I attach a large gpx file, ~ 50 Mb. If the Eliminate GPS outliers is turned on the data is mostly missing. I think (but could be wrong) it is because for a significant about of time we stayed in one place and I am guessing this has biased the algorithm. I was using windows version 7.30. 
To see the effect, turn on the graphs and select in Settings-> Options... -> Data ->Eliminate GPS outliers. Next go to the speed or Elevation graph and click the one not shown to make the map and graph update. The path gets smoothed out more than it should and the graph has large parts of the data missing and replaced with straight lines. Without using this option you can see there are one or two bad GPS speed numbers, but the trace on the map looks good.
[
[trip to Farallons via Drake Bay.zip](https://github.com/tumic0/GPXSee/files/4853614/trip.to.Farallons.via.Drake.Bay.zip)
](url)

**Comment by tumic0** [comment]
The problem is not in the size (with OpenGL enabled it even still works smooth) of the data set, but in the big differences in the data.The outlier elimination algorithm does not work on data that combines two(or more) very different "speed profiles". A typical example where the algorithm fails are ski mountaineering tracks. And your track is a similar case.

I doubt that you can find some universal outlier elimination algorithm that works fine on data from acrobatic planes as well as data from alpine hiking. So while it may be possible to improve the algorithm (some versions ago a sliding window was used to eliminate such cases, but this approach had other problems), the universal solution is simply to disable the elimination on problematic data. (However,  in your case you get unusable speed because of the very strange 6000km/h outlier)

**Comment by Rock2far** [comment]
Thank you for your response. May I make a suggestion the outlier algorithm has a "remove unrealistic data" with options for hiking, boating at sea, boating inland, flying. Each of these have a well defined minimum and maximum altitude and speed. It would be a simpler solution to exclude the odd crazy number. 

  Once again thank you for the response, and I hope the track is at least useful for testing.
  Colin

    On Tuesday, June 30, 2020, 2:31:38 PM PDT, Martin Tůma <notifications@github.com> wrote:  
 
 


The problem is not in the size (with OpenGL enabled it even still works smooth) of the data set, but in the big differences in the data.The outlier elimination algorithm does not work on data that combines two(or more) very different "speed profiles". A typical example where the algorithm fails are ski mountaineering tracks. And your track is a similar case.

I doubt that you can find some universal outlier elimination algorithm that works fine on data from acrobatic planes as well as data from alpine hiking. So while it may be possible to improve the algorithm (some versions ago a sliding window was used to eliminate such cases, but this approach had other problems), the universal solution is simply to disable the elimination on problematic data. (However, in your case you get unusable speed because of the very strange 6000km/h outlier)

**Comment by tumic0** [comment]
The philosophy of GPXSee is, that it shall work without fiddling with some activities setup. It shall be a straightforward universal viewer. However this implies, that it won't fit 100% in many use cases. But that's ok as there will be a specialized SW for that purpose that you should use. (In this case you can use some editing tool to fix the outliers in the data first)
