### ISSUE TITLE
Dark theme on MacOS

### ISSUE THREAD

**Issue by kropochev** [tumic0/GPXSee#298]
![](https://i.imgur.com/1i5clW8.png)

**Comment by tumic0** [comment]
This would most probably get fixed (like other issues with recent OS X systems like #281) with a newer Qt version than 5.9 which is used in the current build, but I get this "showstopper" [bug](https://bugreports.qt.io/browse/QTBUG-81791) with newer Qt versions on my  system (10.13/Xcode 10).

The problem is, my OS X build machine can not run newer XCode versions (that might eventually fix the issue) and until there is some [real interress](https://github.com/sponsors/tumic0) in GPXSee OS X builds, things will only get worse. There will be for example for sure no OS X ARM version of GPXSee with the current state of interress.

**Comment by tumic0** [comment]
But there is a big chance you can fix it yourself by building your own version of GPXSee with a newer Qt version and XCode 11.

**Comment by tumic0** [comment]
Since GPXSee 7.37, the OS X version is compiled with Qt 5.15.2 and the dark mode works fine on OS X 10.15.
