### ISSUE TITLE
GPXSee 7.31 won't launch on macOS 10.15.5

### ISSUE THREAD

**Issue by chwhitaker** [tumic0/GPXSee#300]
Installed GPXSee 7.31 onto MacOS 10.15.5. When I try to run the app, I get:

“GPXSee.app” can’t be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information.

What's up?

**Comment by tumic0** [comment]
From the program homepage (I have highlighted it 06b67283ab155ad811b1c102326b63df1df62a1c to make it more visible):

> On OS X, Apple does not allow software that does not generate them profit like GPXSee to pass OS X's Gatekeeper (you can't import custom certificates) so you need to run the application using the "right click menu" when opening it for the first time.

Apple spreads this "cannot check it for malicious software" FUD about any application that does not generate them profit, to force a more closed and Apple-controlled application ecosystem (the time, when Apple, not you, will decide what applications can be run on your Mac is every year closer, they already did that for the iPhone). Unlike most of the applications, that generate Apple profit through the Appstore, GPXSee is opensource (therefore 100% transparent) and the binaries are signed with a [certificate](https://github.com/tumic0/GPXSee/blob/master/cert/mac/gpxsee.cer) that is available here on Github. Checking the binaries for malware can be done as good as with any application distributed through the Appstore. Contact Apple for more information, why they spread this FUD.

**Comment by fvdm** [comment]
It's 'chain of trust' thing. The certificate in this repo is self-signed and thus untrusted by pretty much all online security standards. You can easily [bypass](https://support.apple.com/en-us/HT202491) this by going to System Preferences > Security & Privacy > General tab > Click the 'Open Anyway' button.

**Comment by tumic0** [comment]
Just out of curiosity, what do you mean by _"all online security standards"_? All the root certificates you have in your browsers/OSs certificate store are self signed as well. It's all about who you trust. And the problem with OS X is, that its Apple who decides who you trust, not you.

**Comment by fvdm** [comment]
"Pretty much all" as in "close to, but not exactly all" online security standards are based on a common trust anchor. For browsers and mail it is the root certs and CAs. Although those areas are very slowly transitioning to TLSA for self signed, but that still relies on a root anchor in DNSSEC. It is always based on trust and Apple is just another entity that can do whatever they want with the keys or the permits. But that also applies to you. It is impossible to know with whom you have shared the private key, intentional or unknowingly, as I don't know anything about you, your security standards or your ethics.

**Comment by tumic0** [comment]
> But that also applies to you. It is impossible to know with whom you have shared the private key, intentional or unknowingly, as I don't know anything about you, your security standards or your ethics.

That's why you can take the sources, check them and compile them yourself. Or you can use the homebrew/macports builds if you trust those projects rather than me. But whether I'm trustworthy or not is not the point here, because even if you would (let's say based on my reputation) like to trust me/my SW builds, you can't and you will get an extra FUD message from Apple instead.

On all Linux distros and even on Windows you can import custom repository keys/software signing certificates according to your will. On OS X, you can't unless I pay Apple one hundred dollars a year.

**Comment by fvdm** [comment]
I get your points and agree, but providing a certificate with your code does not automatically make it more reliable than Apple's signature. It is only slightly more convenient for the user. Same with using a package manager with trusted signatures.

Sure Apple goes too far with their kill switch on apps and even devices. But when someone buys an Apple product they kind of already agree with those methods and business model.

**Comment by tumic0** [comment]
> I get your points and agree, but providing a certificate with your code does not automatically make it more reliable than Apple's signature.

No certificate/code signature makes code more reliable, it just proves the originator. In case of GPXSee, the signature assures (unless the signature/key has been compromised, but that's a problem with any signature), that the builds were made by the same person that owns the source repository.

> But when someone buys an Apple product they kind of already agree with those methods and business model.

Well, I don't. And that's the reason why the software is distributed as it is. Because as long as there is enough relevant SW out there that has not surrendered, it is hard for Apple to close the OS X ecosystem completely like they did with IOS. You will get some FUD messages and need to do some extra work to install/run the software YOU want on your Mac, but it can at least still be done. On IOS you are screwed.
