### ISSUE TITLE
FR - show nearest waypoint details in tooltip

### ISSUE THREAD

**Issue by Peter2121** [tumic0/GPXSee#305]
It is extremely usable for me to be able to see the details of the nearest track point clicking on the track. Actually such tooltip shows the details of the whole track. Ideally, I would like to see the data, related to the nearest waypoint (if this waypoint could be highlighted on the map - it is even better): 
- speed
- altitude (if available) 
- absolute time (UTC or local)

This feature can help to analyze the tracks, notably from aeronautical activity.

**Comment by tumic0** [comment]
The "philosophy" of GPXSee is that you have all this info (except that the time is relative to the track start) in the graphs, where you can move the slider to an arbitrary point of the track. If you desperately need the exact track point info for some special purposes, you have to use a different tool that is designed for "advanced" tasks like QMapShack rather than a simple universal viewer like GPXSee.
