### ISSUE TITLE
ECW Map + Oziexplorer Map calibration support

### ISSUE THREAD

**Issue by jacanestro** [tumic0/GPXSee#316]
Hi!! GPXSee is a great tool. I like it.

Is it possible to use ECW map with a Oziexplorer MAP file? Or the ECW with another calibration file?
If not, have you thought supporting these kind of files?

Thank you and kind regards.

**Comment by tumic0** [comment]
GPXSee supports any image format that is supported by QT (either "out of the box" or in form of a 3rd party plugin like [QtPBFImagePlugin](https://github.com/tumic0/QtPBFImagePlugin)). But AFAIK there is no ECW plugin for Qt, maybe because the proprietary license of the ECW libraries is incompatible with (L)GPL.

Anyway, I will not be the one, who will write such plugin, you have to find someone else or do it your self.

**Comment by jacanestro** [comment]
Ok! Thank you!
I was not asking anyone to do that, neither will I do it. I just wanted to know if there were any plans to support this kind of image. Now I know the answer.
I wish I could help improving this great tool but unfortunately I don't have enough programming skills.
Thank you again and regards again!! ;-)
