### ISSUE TITLE
Garmin IMG maps: wrong slope lines

### ISSUE THREAD

**Issue by sikmir** [tumic0/GPXSee#318]
Slope lines should be drawn on the lower side of a contour line.
Compare:
![scr3](https://user-images.githubusercontent.com/688044/97815202-81ea6f00-1c9d-11eb-84b8-4f0dc9ca3889.jpg)
![scr2](https://user-images.githubusercontent.com/688044/97815210-8c0c6d80-1c9d-11eb-8d29-38dc640c2660.jpg)

**Comment by tumic0** [comment]
Can you provide the map? Slope lines are displayed correctly on maps I have tested (and which have them, such maps are an absolute minority). But that may be just by chance as there is no special handling of non-symmetric line images, except of the chosen angle rotation direction. But I'm not aware of any special flags for such lines.

**Comment by sikmir** [comment]
* https://maptourist.org/ (e.g. [OSM-MapTourist-szfo-RU.zip](https://maptourist.org/osm-garmin/OSM-MapTourist-szfo-RU.zip))
   * GPXSee (incorrect slope lines)
![gpxsee-maptourist](https://user-images.githubusercontent.com/688044/98926989-084a5080-24e9-11eb-85a3-43a6b1d6935f.jpg)
   * QMapShack (correct slope lines)
![qmapshack-maptourist](https://user-images.githubusercontent.com/688044/98926992-097b7d80-24e9-11eb-9d76-5466df357f9b.jpg)
* Vlasenko maps (e.g. [OV-Hib-Lov-20201017-1.03.zip](https://drive.google.com/file/d/17DUaRG_qj_qgIZ5EuHOflaDCobO0pWlv))
   * GPXSee (incorrect slope lines)
![gpxsee-hiblov](https://user-images.githubusercontent.com/688044/98927606-cff74200-24e9-11eb-9dae-9dde09cb32b7.jpg)
   * QMapShack (correct slope lines)
![qmapshack-hiblov](https://user-images.githubusercontent.com/688044/98927609-d08fd880-24e9-11eb-92a7-0d95f30daec1.jpg)

Location: 67.8311, 34.5278 (Angvundaschorr).

**Comment by tumic0** [comment]
After some more investigation it turns out, that GPXSee uses the same algorithm (renders the bitmaps in the same way) as Garmin BaseCamp does, while QMapShack renders them the other way round. And as Garmin maps are rendered correctly (as expected) in BaseCamp I will leave it as it is and be rather compliant with BaseCamp rather than QMapShack.

**Comment by sikmir** [comment]
But what is a root cause? Is it some problem with maps? How BaseCamp renders these maps? I can't check BaseCamp on Linux. That's really wrong rendering no matter what it compliant with.

**Comment by tumic0** [comment]
From what I have seen, the problem is in the maps (and QMapShack). All Garmin produced maps (even with very complex slope lines) I have seen are rendered correctly in BaseCamp (and GPXSee). As there is AFAIK no flag that would describe the rendering of the bitmap lines, the root cause must be in the way (direction) the lines are constructed (and rendered). There will be something like the "Even–odd rule" on how the lines shall be constructed and later rendered and mkgmap (or cGpsmapper, I didn't searched for the creator SW of the maps) as well as QMapShack are using the wrong way.

OSM maps with asymmetric bitmap lines are extremely rare so no one has fixed or even realized it yet.

**Comment by sikmir** [comment]
Well, but what is not clear why these maps are rendered correctly on Garmin devices.

**Comment by tumic0** [comment]
If BaseCamp renders the maps differently than some/the devices than this would indicate that Garmin itself has problems with consistency of map generation/rendering across his products (would not surprise me after all I have seen...). And there is thus no way at all to render (all) the maps correctly.
