### ISSUE TITLE
FIT file display

### ISSUE THREAD

**Issue by dpawlyk** [tumic0/GPXSee#320]
This contains a FIT file that was produced by GPSBabel from a GPX file. It opens in Garmin BaseCamp.

It doesn't open in GPXSee.

[GRX-Market_Basket_to_Boonton_2.zip](https://github.com/tumic0/GPXSee/files/5490673/GRX-Market_Basket_to_Boonton_2.zip)

**Comment by tumic0** [comment]
The reason, why it does not work are the broken timestamps in the file. For some reason that I do no more remember, duplicate time entries are dropped in the FIT parser since a fix/workaround for the obscure Bryton Rider FIT files. Even for formats where such broken timestamps are "enabled" you get very strange results, but at least you see the track on the map. I will investigate this further and eventually enable such broken files, but generally one should not expect that a program will read arbitrarily broken files even when another program generates/reads them...

**Comment by tumic0** [comment]
I have removed the special check in the FIT parser in 731b309ac9a947b9f05a5a853922908fc6d08a55, so you get now the same behaviour like on GPX files with broken timestamps - a lot of console warnings, but at least some useful info like the track and distance based graphs.
