### ISSUE TITLE
FR: map file passed through command-line arguments

### ISSUE THREAD

**Issue by sikmir** [tumic0/GPXSee#327]
It would be great if GPXSee could load map files passed through command-line arguments on starup, just like data files. What about use case: I have a lot of map files (img, jnx, xml) and a lot of data files (gpx), often I just want to open some track with some map from command line without adding that map to `~/.local/share/gpxsee/maps` permanently.
Currently I do:
1. `gpxsee track.gpx`
2. `Map -> Load map...`, choose map file

But it would be really cool to run:
1. `gpxsee track.gpx map.jnx`

**Comment by tumic0** [comment]
Well, this is quite high on my "One day, GPXSee should be able to do this" list :-). Not exactly because of opening a combination of maps/files, but because with that many map formats supported (with some formats quite unique in the open source world), people should be able to use GPXSee as a regular map file viewer. And by regular I mean "simply clicking on the file to open" in the file manager.

The question is, how hard will it be to combine the two file types (maps/data) internally in the program logic as this was not intended from the beginning.
