### ISSUE TITLE
Start program window maximized

### ISSUE THREAD

**Issue by tamas-ferenci** [tumic0/GPXSee#328]
It might a matter of taste and personal preference, but it is strange that the GPXSee window opens with a very large size, but not maximized. Wouldn't it be better to start as maximized? (At least I always maximize it as a first step before I do anything.)

**Comment by BernieStn** [comment]
I fully agree with this issue. Typically, when I want to close an application, I move the mouse pointer to the right upper corner and click the X in the window title. I do this without even looking at the screen, because it works same for all applications.
With GPXSee it doesn't work that easily, because the X is not always in the right upper corner of the screen.
It would be really nice if the application can start maximized, or at least in the same size as it was when it was closed before.

**Comment by tumic0** [comment]
The problem is, starting maximized does not work with all window managers, especially with fluxbox that I'm using. So rather than not working for me at all, I choose a little glitch for others until there is some solution that works for all of us.

**Comment by BernieStn** [comment]
Thanks tumic0 for your reply. I understand that most likely not every window manager may be able to start an application maximized, but on Windows there is only one Window manager (as far as I know). So probably it would be a solution to implement the behavior in a way that maximizing always works on Windows.
