### ISSUE TITLE
[request] network socket position string

### ISSUE THREAD

**Issue by halftux** [tumic0/GPXSee#34]
What do you think about the idea to listen to a network socket for getting lat long values (some defined string)  which will be shown as a position on the map, and maybe also get centered.

**Comment by tumic0** [comment]
Well... I was thinking about showing the current position several times, but the problem is, there is no nice and clean solution to do this. There is QT positioning, but I don't like the idea to make GPXSee dependent on that module. After all, it is a desktop application and the main purpose is to show GPS logs, not navigation.

Reading some universal format from the network would be nice, but there is no common infrastructure available on the supported platforms  - GPSd has screwed the NMEA multiplexing by requiring some weird JSON interaction before NMEA data are received on the socket and I don't know about any common similar SW for Windows at all...

**Comment by halftux** [comment]
Some navigation is not needed but I think maybe the possibility to show an extra POI which coordinates are typed by user input. This could be a nice extra feature. Don't need to come from network, instead from a dialog or something.

**Comment by tumic0** [comment]
Yes, this is something in my plans, to ad an "Open custom location" under the "File" menu with a dialogue for inserting custom coordinates.

**Comment by edegraaff** [comment]
Hi, it would be great when you could add an NMEA source. I have asked the author of BSGPS to share his knowledge on this, since he uses the input of an external NMEA device. Also ozi explorer is capable of reading an external source and even supports garmin gps-es as external source. This way the software can also used on ships, since they often use nmea. GPS receivers that can be added to your usb or rs232 port have become cheap, 15-50 euro.  That way you have an accurate gps device with large screen, and optimal maps :). Willing to test for you.

**Comment by edegraaff** [comment]
I am sorry i am not a programmer but maybe this give some thoughts
https://gpsd.gitlab.io/gpsd/index.html
https://github.com/VisualGPS/VisualGPSqt

**Comment by tumic0** [comment]
Added in fa55c6d93a0d20af9a571322dc9c9d6dc246d3a5 (using Qt positioning)
