### ISSUE TITLE
FR: show indicator on track when moving along the graph

### ISSUE THREAD

**Issue by Tux** [tumic0/GPXSee#348]
I know I saw it somewhere somtime, and I was sure it was GPXsee, but its gone.
When dragging the cursor along the graph at the bottom, it would be wonderful to see a small indicator moving along with it on the track on the map. Be it a cross or a coloured dot is both very informative and helpful. The milage indicators also help, but we have a maximum distance for one of the hikers (a dog), so we need to find a parking place within that distance, but rather close to the max. Dragging along the line within the margin of that max shows on the map where to zoom in.

Thanks for creating this awesome tool!

**Comment by tumic0** [comment]
The marker is still there, you can enable/disable it under the "Data" menu. Since recently you can also configure some info for the marker so this is why the configuration menu has changed a little bit. If you can not see the marker (in the latest GPXSee version - 8.7) even when it is enabled in the menu, then provide some more info like your OS, the data file you are using, etc. Otherwise there is nothing I can do about it.

**Comment by Tux** [comment]
I found that menu entry, but none of the options shows anything when I drag the line. Sorry.
(I even recompiled from git, just to be sure)

**Comment by tumic0** [comment]
There was indeed yet another bug of the path<->graph connection logic (which had completely changed when the marker info was introduced) that caused the issue. Thanks for reporting.

**Comment by Tux** [comment]
WOW! YES! Wonderful! Confirmed (tested from git)
