### ISSUE TITLE
[feature request] stacked maps in menu

### ISSUE THREAD

**Issue by Tux** [tumic0/GPXSee#362]
If I create `~/.local/share/gpxsee/maps` with a supported set of maps, the default selection disappears from the Maps menu.
```
$ cd ~/.local/share/gpxsee/maps
$ ln -s /usr/share/gpxsee/maps/* .
```
The entries are available again (and work as expected).
I think that `~/.local/share/gpxsee/*` should overrule `/usr/share/gpxsee/*` and not disable them.

**Comment by sikmir** [comment]
> I think that `~/.local/share/gpxsee/*` should overrule `/usr/share/gpxsee/*` and not disable them.

In such case, how to disable default maps?

**Comment by tumic0** [comment]
> In such case, how to disable default maps?

Exactly.

The user directory "replaces" the system directory because otherwise you could not disable some maps that you don't want in the menu. If you want to extend the system maps, you can simply copy them to the user directory (the xml files are a few bytes) or make a symlink in case of offline maps.

**Comment by Tux** [comment]
I cannot imagine someone to *not* want the default maps in their menu, but I can live with this.
Still think it might be something to put in options.

**Comment by tumic0** [comment]
https://xkcd.com/1172/
