### ISSUE TITLE
[feature request] have an option to set the default map

### ISSUE THREAD

**Issue by Tux** [tumic0/GPXSee#363]
When I select a map from the map manu, it doesn't "stick". Next time I start gpxsee, it will select the original default map (again).
I want to keep the liberty to change the map (I do so quite often), but I'd also like to have the ability to select a default map, which would be used on initial view when I start gpxsee. Would fit perfect in Options->Maps

**Comment by tumic0** [comment]
The last used map should be remembered by GPXSee and used the next time, when GPXSee starts (if the map is available = in the `maps` directory). If that doesn't work, than there is something wrong in GPXSee.

Is there some error message in the console? How does your `maps` dir look like? Please provide some more info, otherwise there is not much I can do about it (works for me).

**Comment by Tux** [comment]
Now it does.
Must have been me playing with the new map format.
Sorry for the noise.
