### ISSUE TITLE
Support for Ubuntu 21.04

### ISSUE THREAD

**Issue by Aresthedog** [tumic0/GPXSee#369]
Please add support for Ubuntu 21.04

**Comment by tumic0** [comment]
What do you mean by "support for Ubuntu 21.04"? GPXSee should work fine on Ubuntu 21.04, there is even already a package build script for it at the GPXSee [OBS project page](https://build.opensuse.org/package/show/home:tumic:GPXSee/gpxsee). It does however not work at the moment because OBS's Ubuntu 21.04 installation is broken. If you mean that, than you can try to make people from SUSE fix it by reporting that issue (which is not that easy as they only use some obscure mailing lists that do not work half the time...). Or you can of course try to make Ubuntu people to create an official package for GPXSee and make it part of their distribution like it is the case for every other modern linux distribution.

But from GPXSee's side, there is nothing to fix.
