### ISSUE TITLE
10 Hz GPX files 

### ISSUE THREAD

**Issue by tytoalba99** [tumic0/GPXSee#407]
Hi,

The application has problems to render 10 Hz (samples per second) GPX files. When I extract the coordinates from a Gopro Hero 5 video straight lines are rendered. 
See the comparison from the same GPX file in GPXsee and Adze Lite. Imagery is different (Google vs OSM) but you can see the different path.

Congratulations for the application as I use a lot.

![Captura de pantalla 2021-11-09 a las 11 42 06](https://user-images.githubusercontent.com/11778076/140912075-f400fea6-d360-450b-98ef-f9bc75aa50fe.png)
![Captura de pantalla 2021-11-09 a las 11 44 13](https://user-images.githubusercontent.com/11778076/140912081-a70169b1-f0d1-4f4f-8da5-bceafe7a2105.png)

**Comment by tumic0** [comment]
Please provide a sample GPX file, otherwise there is nothing I can do about it.

**Comment by tytoalba99** [comment]
Please find attached a sample file. Note the original date and origin coordinates have been altered por privacy.
[GP3610B.lrv EDITED.gpx.zip](https://github.com/tumic0/GPXSee/files/7505924/GP3610B.lrv.EDITED.gpx.zip)

**Comment by tumic0** [comment]
The provided data file does not contain any sub-second time info. It only contains broken data with multiple positions at the same time. If an application does display the data in some way, than it must do some "magic guessing" instead of working with the actual data.

The creator of the file is however gpxgo, not Gopro Hero according to the header, so it is hard to say, if the data was already broken in the original source or was crippled during some conversion. Anyway, you should report the issue to the creator of the data, that shall use proper time fractions as specified in xsd:dateTime/GPX specification and not produce broken files with multiple positions at the same time.

**Comment by Blittr** [comment]
Indeed: I also think that the original correct GPX of Gopro Hero has been corrupted by editing it incorrectly afterwards. Out of the 1722 position-timestamps, only 95 are unique. If you remove the timestamps (with a macro in Notepad++) it works fine, see screenshot. 
@tumic0: : is it officially allowed to remove the timestamp per position form a GPX-file?

![track](https://user-images.githubusercontent.com/93733216/141089050-c09b90c1-333b-4988-9cf4-b8930b80bb32.jpg)

**Comment by tytoalba99** [comment]
I know the GPX may be not very well formed (i’m not the author). And the high frequency of samples the Gopro creates at low speed may difficult it even more.
But all my GPS related applications handle them very well: Garmin Basecamp, Trailrunner,….

![Captura de pantalla 2021-11-10 a las 11 01 40](https://user-images.githubusercontent.com/11778076/141093215-2b24018d-7dec-49c0-bf9e-ac2f7ec71d9a.png)
![Captura de pantalla 2021-11-09 a las 16 37 13](https://user-images.githubusercontent.com/11778076/141093231-9906ecf7-8cc7-4816-8611-37bb91635351.png)
![Captura de pantalla 2021-11-09 a las 16 37 49](https://user-images.githubusercontent.com/11778076/141093235-43a0e0f4-b25f-4cf8-8935-3b542fbff510.png)

**Comment by tytoalba99** [comment]
> Indeed: I also think that the original correct GPX of Gopro Hero has been corrupted by editing it incorrectly afterwards. Out of the 1722 position-timestamps, only 95 are unique. If you remove the timestamps (with a macro in Notepad++) it works fine, see screenshot. @tumic0: is it officially allowed to remove the timestamp per position from a GPX-file?
> 
> ![track](https://user-images.githubusercontent.com/93733216/141089916-027060d3-c05b-4d4a-9765-321956aac0a3.jpg)

Just changed year and month, and main degree values.

**Comment by tumic0** [comment]
GPXSee can also display the file "correctly", but you have to set the pause detection parameters manually (with min. speed 0.1km/h you get the same results as on your images). It's just that the default auto-adjust algorithm based on data statistics fails, if your data is garbage like in the sample file.

If you wonder, why pause detection matters, than it is because GPXSee filters all the movements during the pause period, so your distance/route gets not affected by the "GPS error movements" during that time.

**Comment by tytoalba99** [comment]
Solved changing the speed settings !
Thank you
