### ISSUE TITLE
Copy numerical values shown in Graph to clipboard

### ISSUE THREAD

**Issue by Blittr** [tumic0/GPXSee#409]
Hi Martin, is it possible to make the numerical values shown in Graph (for example ascent, descent, maximum, minimum, see screenshot below) available to copy to the clip board for further processing? Like this: right click on graphics Elevation / Speed and then select "copy values to clip board".

![values](https://user-images.githubusercontent.com/93733216/142774946-3b618012-5329-4ba9-901d-6aeded1b6fe5.jpg)

Thank you and best regards

**Comment by tumic0** [comment]
In the graphs it is not possible, but you can copy all the info from the statistics window (File->Statistics...). _Ctrl+a_ and _Ctrl+c_ works there.

**Comment by Blittr** [comment]
Thank you for the reply. I did not know that. Is is possible to show the name of the gpx-file in the statistics? As the statistics are made up in HTML I can collect all the statistics in one file and then copy the respective values out of it afterwards. Copying from the HTML-coded file is not easy. Extending the tag <h3>Statistics</h3> with the gpx file name, can avoid copying the wrong values.

**Comment by tumic0** [comment]
The problem is, there can be more files open... One could of course again, like on some other places like the status bar, differentiate the output, but here it looks quite strange and ugly. The main problem is, you are trying to use GPXSee for something that it is not intended and for which there are other, better, tools and that is batch processing of GPX files.
