### ISSUE TITLE
some .TRK file not loading with timing error

### ISSUE THREAD

**Issue by JoelErin** [tumic0/GPXSee#416]
Hi,
Most of .trk file are now uploading properly after last update. Thanks for that and for your quick implementation.

Nevertheless, some .trk are not loading properly.
Error message is "Error Loading data file - Invalid date/time line xxx"
Attached is one example of such a file.
It seems only first line is showing date/time, in all other lines time stamp is shown as  00-NUL-00 00:00:00.000 in the file.
It does obviously mean, in such a case, speed and timing cannot be displayed, but trace should be made visible. At least what I would consider to be fair as a 'basic user'.
Many many thanks for help. Joel

[Abbaye de chateliers - St Marie - Abbaye des chateliers.zip](https://github.com/tumic0/GPXSee/files/7803171/Abbaye.de.chateliers.-.St.Marie.-.Abbaye.des.chateliers.zip)

**Comment by tumic0** [comment]
The problem is, there are to few TRK files out there in the "public internet" to test the parser (and as usual, no format specification exists)... All files I have seen use some kind of nonsense, but valid date like 1.1.1962 (or 2062, the year has only two digits). So if you have some more "special" files, then please provide some samples. According to some "rumors", there shall be for example files, that use UTM instead of lat/lon coordinates, but I could not find any such sample.

**Comment by JoelErin** [comment]
Please find attached examples of .trk files I have on my PC.
They come from various sources : some from GPS, some were created with Land (Twonaw application).
Please note track "PG MN 20200315_RBK.trk" is a special one, where direction instructions (lines started with a 'a') where added to the original file. Either parser should disregard these line, or either you do not support such a file (as original file should exist...).
Any question or extra files, feel free to ask.
Joel

[Example of trk track.zip](https://github.com/tumic0/GPXSee/files/7806600/Example.of.trk.track.zip)

**Comment by tumic0** [comment]
Thanks for the sample files. All of them work properly with the latest code changes.

**Comment by JoelErin** [comment]
Hi,
I confirm version 10.2 is working with all the .trk file I had been able to locate on my hard disk. Thanks for having sorted this out.
Joel
