### ISSUE TITLE
GPI file fails to open

### ISSUE THREAD

**Issue by dpawlyk** [tumic0/GPXSee#423]
GPI file produced by GPSBabel fails to open in GPXSee.

"C:\Program Files (x86)\GPSBabel\GPSBabel.exe" -i gpx -f "Starts.gpx" -o garmin_gpi,bitmap="poiblockgreen.bmp" -f "Stops.gpx" -o garmin_gpi,bitmap="poiblockgred.bmp" -F "BTCNJ-locations.gpi
[BTCNJ-Locations.zip](https://github.com/tumic0/GPXSee/files/7909043/BTCNJ-Locations.zip)
"

**Comment by tumic0** [comment]
What version of GPSBabel do you have? The 1.7.0 version on my Arch linux produces correctly terminated GPI files. But I have not your input files, maybe the problem is related to the files. Can you please provide them?

**Comment by dpawlyk** [comment]
1.7.0 for GPSBabel.

Here's everything.

[BTCNJ-Locations.zip](https://github.com/tumic0/GPXSee/files/7909777/BTCNJ-Locations.zip)

**Comment by tumic0** [comment]
The problem is in the image file(s). GPSbabel does not "encode" the provided image correctly, that's why you see a broken image on your device and the error message in GPXSee (which does handle the file format errors in a different way). And why I could not reproduce it with my test files (my test images are handled correctly by GPSBabel).

So the solution is to create a bug report in GPSBabel and provide the image(s) to them. You may also point them to this issue, but I haven't analyzed the GPSBabel code, all I know is they write an image header stating there is a color palette, but do not actually write the palette.
