### ISSUE TITLE
Garmin GPI file speed decoding probably wrong

### ISSUE THREAD

**Issue by ismo-s** [tumic0/GPXSee#425]
The file gpiparser.cpp has function speed(quint8 flags). It uses 4 upper bits for speed decoding but after testing with known camera locations I suspect that the decoding should be done with 5 uppermost bits. 
When the flags are 0xB8 the speed should be 70 km/k and 0xB0 equals to 60.  0xA8 == 50. 
0xD0 is also 100 km/h.  In finland I've never seen speed limit 90. In Sweden they exist but i rarely drive there so can not verify the flags.

Also the camera locations are interesting, there are actually 2 points and one defines the starting area for the camera and second one is the real camera location. I can share the modified code in case somebody is interested.

The lowest 2 bits are 0x03 when the camera is portable ( there are two bits and they seem to be always on when set. Maybe just on is needed but I need to drive to some camera locations and se what the Garmin unit itself decodes there.

I modified the gpxsee (older version , newest does not link on Fedora 34 correcly , qt6, someting about missing libxkbcommon, it sems to be incompatible ) to display flags on the tooltip.

**Comment by tumic0** [comment]
I have changed the speed info parsing in 6b2bb96be708ff4dfda19da95990adcdf951cd14. This looks more likely than the old algorithm. At the time I was fiddling with the speed cameras, the data I had did not fit (they still do not fit everywhere) to this kind of parsing, but that might be a problem of the data. With the old algorithm there were too places, where I would expect a different value...

**Comment by tumic0** [comment]
> Also the camera locations are interesting, there are actually 2 points and one defines the starting area for the camera and second one is the real camera location. I can share the modified code in case somebody is interested.

The camera location data/algorithm is AFAIK a little bit more complex, but the problem is, how to display the info in a viewer that is designed to show points/areas/tracks. At the moment the "danger area" bounding rect and the exact location of the starting camera should be shown. If you have come up with something better, I would like to see your code/results.

> The lowest 2 bits are 0x03 when the camera is portable ( there are two bits and they seem to be always on when set. Maybe just on is needed but I need to drive to some camera locations and se what the Garmin unit itself decodes there.

The lower two bits are indeed somehow connected with the kind of the camera. I have seen all the possible values (0-3). The question is whether it is worth to research more on this topic and extend the waypoint description...

> newest does not link on Fedora 34 correcly , qt6, someting about missing libxkbcommon

At least the qt5 build should work as there is an official 10.1 build for Fedora created by RedHat. And the qt6 build should also work, Archlinux uses qt6 for their builds and they work fine...

**Comment by tumic0** [comment]
It turns out bits 2-6 are used for the speed info and bit 0 is the portable camera/danger area flag. Bit 1 is most probably a enabled/disabled bit for permanent cameras, but the data for my location is so full of errors, that it is hard to be sure here...
In 69ebac9f5d9bd8d3c34938c7ce8b7964b1e574c2 this findings are translated into a better info code.
