### ISSUE TITLE
French | English menu consistency

### ISSUE THREAD

**Issue by pbstudent** [tumic0/GPXSee#446]
File -> Help in English
GPXSee menu in French:
<img width="228" alt="2022-08-02_12-22-36" src="https://user-images.githubusercontent.com/24277755/182362698-fc7b5778-1389-4be7-9d97-5e5ffbffaa79.png">

**Comment by tumic0** [comment]
AFAIK there is some text-based heuristics in Qt on Mac that puts some items under "special" menu entries. So there may be some differences in the placement on Mac when the original text matches some of the heuristics and the translation does not (or vice versa). Maybe some more fiddling with the menu roles could help, but the question is whether it is worth spending time on it. Is there some "real" problem with the placement/inconsistency?

**Comment by pbstudent** [comment]
Normally a software is all in the same language, this is the first I have ever seen that is a mix of French and English.

**Comment by pbstudent** [comment]
Normally a software is all in the same language, this is the first I have ever seen that is a mix of French and English.

**Comment by tumic0** [comment]
I have looked again on that picture and now I can see what the real problem is. The english/french mix is simply caused by a missing french localization. The strings you see in french are provided by the OS which is set to french. The rest is provided by GPXSee and should theoretically also be in french as GPXSee has a french localization, but for some reason it was not selected.

The bad news is, that this looks like another instance of #137, #268 or #426. TLDR - there is not much I can do about it.
