### ISSUE TITLE
Samsung Galaxy Note 20 Snapdragon hangs on loading files/folders

### ISSUE THREAD

**Issue by rontoups** [tumic0/GPXSee#447]
I've downloaded GPXSee for Android and only get a black screen with the GPXSee top border when I attempt to load any file or folder to view. The app seems to hang and the only way I can try again is to close the app and start over. It has never worked successfully since downloading.

I'm trying this on a Samsung Galaxy Note 20 Ultra (Snapdragon) and have tried with geotagged image files and .tcx files. 

These same files work successfully on GPXSee for Windows.

Any ideas what I can try to resolve this issue?

**Comment by tumic0** [comment]
Can you please provide the complete first row of the "Help->About GPXSee" dialogue that shows the exact version and target platform? There may be some problem with the arm64-v8a build that I'm not able to test due to lack of such HW. The phone should be arm64 capable, but I have no idea how Google chooses what to install from the play store.
