### ISSUE TITLE
Oversized GUI on Windows 11

### ISSUE THREAD

**Issue by jay0pi0** [tumic0/GPXSee#453]
Since 11.2 or 11.3, the GUI is enormously huge on Windows 11. I'm on a 1920 × 1080 laptop with a touchscreen. I think it was more compact in previous releases. Tried all the scaling options via right-click on the .exe icon / properties / compatibility / change high DPI settings, they have no effect and/or make the GUI blurry.

Is there a possibility to implement a GUI scaling option?

<img width="960" alt="Unbenannt" src="https://user-images.githubusercontent.com/113432715/189878083-e4cfc8d2-45f1-4d8c-a70b-06ce21dbb1ff.png">

**Comment by tumic0** [comment]
Nothing has changed in GPXSee in this area at least since 11.0 (in fact much, much longer), so the change will most probably be due to some change, e.g. DPI setting on your system. Unfortunately I do not have a Windows 11 nor a HiDPI Windows machine to fiddle with them, so there is not much I can do here...

**Comment by jay0pi0** [comment]
Alright, I am a bit ashamed now... 🙈 I connected my laptop to an external monitor again (did not do that for a longer time, it has more pixels) - looks much better 😏. On my rather smallish laptop screen I should indeed simply change the Windows 11 scaling. Nothing wrong with GPXSee.
