### ISSUE TITLE
Feature reguest - would it be possible for the waypoint description shown on the map correctly display line breaks &lt;br&gt;?

### ISSUE THREAD

**Issue by mwrnckx** [tumic0/GPXSee#507]
![obrazek](https://github.com/tumic0/GPXSee/assets/141876172/2bb6b568-2a5e-4276-83dc-850b4279d98c)
`<name>First line of name&lt;br&gt;Second line of name</name>`

**Comment by tumic0** [comment]
The one-line variant shown on the map is used because of display performance. Wrapping the text and computing the bounding boxes is much slower when the text is multi-line. The `name` attributes are generally expected to be short and in plaintext (the GPX standard does not officially support HTML markdown there). In the info box we can do arbitrary text processing as performance does not matter there and many formats use HTML in the description (note, that there is officially no HTML in GPX even in the `description` tag).

There could be some setting for enabling wrapping even on the map but I'm not sure it is even worth to fiddle with it. Moreover, I really do not want to encourage people to use some long, multi-line, waypoint names as long text simply belongs into the description.
