### ISSUE TITLE
Add + and - zoom buttons

### ISSUE THREAD

**Issue by jidanni** [tumic0/GPXSee#515]
Add (optional) + and - zoom buttons.
Because sometimes using ones fingers isn't too convenient.

**Comment by tumic0** [comment]
This was already discussed several times here and my position is still the same - I do not want to wast the usable display space for the buttons. On desktops, this is "undisputed", the keyboard/mouse control for that is sufficient. On mobile devices (Android) this is another story, but due to the fact how broken all the stuff in Qt/Android is, I do not want to spentd any extra time with stuff special for this platform until absolutely necessary. Which is not this case.

**Comment by jidanni** [comment]
(On chromebook we install android apps onto the "desktop".)
