### ISSUE TITLE
Allow controlling initial zoom, location, etc. from the command line

### ISSUE THREAD

**Issue by jidanni** [tumic0/GPXSee#518]
Perhaps allow controlling initial zoom, location, etc. from the command line, like
https://man.archlinux.org/man/viking.1.en

**Comment by tumic0** [comment]
Sorry, but I do not see any usage for that that would justify the costs of development. Like with all other special wishes - unless there is a broad usecase you have to implement it yourself in your own fork.

**Comment by jidanni** [comment]
I'm just saying if the program could be made able to be controlled totally without needing finger input, one could
use it for

- kisok automated displays
- disabled user access
- rapid viewing of KML results
- batch job image production
- a CLI API,,

 the possibilities are endless.

**Comment by tumic0** [comment]
Some sort of "live tracking system" like discussed in #337 may come some day, but what you describe is rather a CLI tool which is simply out of scope of GPXSee. Sure, someone could design that on the basis of GPXSee, but the purpose of GPXSee is to be a simple viewer, not a complicated GIS tool (many of which already exist).

**Comment by jidanni** [comment]
Yes, that's all I want to use it as, a quick read-only viewer. It's at the bottom of a makefile as the last step after I produce a kml. In emacs.

I'm thinking of where I would never have to even touch a mouse, or edit a configuration file. I would have everything (settings)  I need right there changeable on the command line.

That way it would be super portable, just install and use.

**Comment by eddy-geek** [comment]
ideas for a workarounds:
* settings that are remembered by gpxsee accross launches could be edited in the gpxsee.conf file prior to launching it -- so a simple wrapper program could be done to automate this.
  * unfortunately only the map is remembered right now, not location & zoom. @tumic0 is remembering location & zoom on your radar?
* since gpxsee tries to fit the gpx track given as input, a simple gpx can be made with the location(s) to show.
