### ISSUE TITLE
Part of a track is shown as a single line

### ISSUE THREAD

**Issue by hemmingway-1** [tumic0/GPXSee#521]
This part is shown correctly by RouteConverter.
The part is added manually in RouteConverter.
Before adding it was a single line.
![GPXSee](https://github.com/tumic0/GPXSee/assets/39398145/4986cfc2-ec96-4eab-9193-83242ce80e55)
![RouteConverter](https://github.com/tumic0/GPXSee/assets/39398145/1c0bd229-a3bd-4175-b96e-6e13ea4ca110)
[Flamingoroute.csv](https://github.com/tumic0/GPXSee/files/12747552/Flamingoroute.csv)
The csv file is a gpx file.

**Comment by tumic0** [comment]
GPXSee is designed to work with real data, not the nonsense you have in your data file. Because of the nonsense timestamps in your data, the pause detection algorithm evaluates this part of track as a pause and "filters" the path. You may switch the pause detection to manual and set the minimal speed to 0.1km/h to get the "desired" route, but in general GPXSee is not the right tool for working with artificial, broken-by-design (you have even time skews in your data where the time goes backward...) data. You better use some tool like RouteConverter that does not care about the "physics" of the track and does not use any statistics methods to filter data or handle workout pauses like GPXSee.

**Comment by hemmingway-1** [comment]
Your note works for me.
So I can compare two tracks with different colors.
Thank you for your work, Bernhard
