### ISSUE TITLE
The link in the Android application is not clickable

### ISSUE THREAD

**Issue by snooppr** [tumic0/GPXSee#524]
OS Android 9 (LOS16)
GPXSee v13.11 (arm qt 6.4.0)

Click the 3 dots in the upper right corner, then “help”, then about “GPXSee” the license for the project and a link to the site “www.gpxsee.org” will be displayed.  The link is highlighted in color but it is not clickable, this somewhat reduces the traffic/popularity of the project.

**Comment by tumic0** [comment]
This is yet another Qt bug on Android. You may report it in the Qt bugtracker, but chances someone will care are low, given the amount of much more serious Qt bugs on Android. It may also be fixed in some newer Qt version, but no newer Qt version can be used in GPXsee due to bugs like "files can not be open" in versions after 6.4.0.
