### ISSUE TITLE
SkyDemon created track GPX only showing first-last trkpt

### ISSUE THREAD

**Issue by rescalda** [tumic0/GPXSee#538]
The aeronautical application Skydemon can export a track in .GPX format. Opening that .GPX with GPXSee I only see (almost) a line between the first and last track points. Speed and altitude diagrams are inconsistent too. Should I load that GPX into Google Earth I see it correctly. But, curiously, should I export the imported GPX in KML and open the KML with GPXSee, I see it correctly! 
I gave a quick look inside the GPX and I noticed it is very basic with, apparently, nothing strange that can lead to such behavior!
I attach the _incriminated_ .gpx (zipped).
[Arezzo.zip](https://github.com/tumic0/GPXSee/files/14930096/Arezzo.zip)

**Comment by tumic0** [comment]
The problem is your record is quiet unusual ( ~1h of flight and ~5h of standing on the ground) which breaks the outlier elimination algorithm (which [is sensitive to data with very different speed profiles](https://www.gpxsee.org/doc.html#filtering)) that is enabled by default. If you disable outlier elimination in the options (Data->Filtering->Eliminate GPS outliers), you will get the expected route.

You may also strip the 5h of standing on the ground from the log file (which is probably what your GPX -> KML conversion did) and than it works fine even with outlier elimination enabled.
