### ISSUE TITLE
Issue with Komoot exported GPX tracks

### ISSUE THREAD

**Issue by mydani** [tumic0/GPXSee#557]
Hi,
with the most recent version exported tracks from Komoot do show up as straight line of 10m length.
Example GPX attached.

[2023-06-11_e_mtb_1163078065_1720344642.zip](https://github.com/user-attachments/files/16827613/2023-06-11_e_mtb_1163078065_1720344642.zip)

**Comment by tumic0** [comment]
Nothig has changed in GPXSee, the problem is in the data. Your GPX file has some broken/artificial timestamps that state you have traveled the 46km 4.5 months... This gives an average speed << 0.1km/h which is detected as a pause and discarded (GPXSee discards moves during pauses).

As you are not the first one with such garbage data, I have added the option to disable the pause detection to GPXSee in 7e690bdbfb8a08f59047c42f526d6a5f67379147 so you can configure GPXSee to display even such data. But in almost all cases one should rather fix the producer...
