### ISSUE TITLE
How to access offline maps

### ISSUE THREAD

**Issue by nick51** [tumic0/GPXSee#561]
I am running Windows 11. Programs are stored in partition F: and data is stored in partition E: 
My version of GPXSee (version 13.24) is loaded as F:\Program_Files\GPXSee.exe. I am trying to access offline maps stored in path E:\Hiking\Maps.

According to the documentation:
Two kinds of maps are supported by GPXSee - online maps and offline maps. You may either load them
"ad hoc" from the GUI or they can be loaded automatically at program startup from the maps directory. The
map directory is recursively searched when loading the maps, so it may contain an arbitrary directory
structure (which will be preserved in the map menu).

However, I cannot find information that gives me the path to that maps directory. There is a path F:\Program_Files\GPXSee\maps, which I have tried to use.

I have a map in folder "E:\Hiking\Maps\_Africa\Garmin\SA Topo Rec 2012v1.gmap". In that folder is a file Info.xml
If I use the GPXSee toolbar to load that map, by pointing to file Info.xml as above, I am successful. But I would like to be able to access that map every time I run GPXSee.

The xml files for online maps are stored in folder F:\Program_Files\GPXSee\maps, and I have tried creating a shortcut to file Info.xml in that same folder. That does not work - in the maps dropdown, all that I see is 'SA Topo Rec 2012v1.gmap.lnk'. If I click that, nothing happens. According to the Help, the map directory path is C:/Users/Nick/AppData/Roaming/GPXSee/maps, but there is no entry for GPXSee in C:/Users/Nick/AppData/Roaming/

Essentially, I have four questions:
1. What is the name of the folder should contain the file that contains the information that gives GPXSee the details necessary to load a given offline map?
2. Where is that folder located?
3. What is the name of that file?
4. What information should that file contain?

I should be very grateful if you can tell me what I am doing wrong.

**Comment by tumic0** [comment]
The exact path of the user maps directory is the path shown in "Help->Paths", in your case `C:/Users/Nick/AppData/Roaming/GPXSee/maps`. If the path does not exist, simply create the directory and put the desired maps there. If you want your maps somewhere else, you can create a directory symbolic link at the path instead of a directory. Note that by "symbolic link"  I mean a real [symbolic link](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/mklink) as created by `mklink /d`, not a desktop shortcut (*.lnk) file like you did.

**Comment by nick51** [comment]
Thank you!  I appreciate the swift response. I have tried both approaches
(full map folder and symbolic link) on my laptop and both are working.

Regards
Nick Corbin
+27828546533
