### ISSUE TITLE
Elevation

### ISSUE THREAD

**Issue by bmili** [tumic0/GPXSee#566]
![Posnetek zaslona 2024-10-05 231129](https://github.com/user-attachments/assets/d48d5eed-cb4a-4771-bf1c-c57ac5b4c622)
Why is elavation in GPXsee  100m  bigger as in GPXstudio?

Boris

**Comment by tumic0** [comment]
The difference is caused by different elevation computation, different data used or both. Different programs use different data smoothing (you can set it up in GPXSee and get almost every elevation you wish) when computing the elevation. There is also usually a big difference between the GPS and DEM data and even various DEM sources (you can switch the elevation source in GPXSee and even use an arbitrary DEM source).

You should understand the data and use the most suitable data source and data smoothing for your use case. GPXSee is designed to make this possible. If you don't care, you will get "some default number" which is different in every single application/web service as there is no single "correct way" how to show the elevation for a particular track.
