### ISSUE TITLE
Feature request: increase the display distance resolution

### ISSUE THREAD

**Issue by harrywalther** [tumic0/GPXSee#568]
Hi, 
I have asked for this before a few years back. I use gpxsee a lot to measure trail distances, sometimes for races, sometimes just for myself. Back then, your reply was that GPS devices can't be trusted below a resolution of 1/10 of a mile and since it's your project I just patched the code for my personal use (no problem there, thank you for keeping gpxsee open source.)

However, since then things have changed. The advent of dual-frequency devices has definitely pushed the reliability of distance measurement way below 1/10 of a mile (or, for that matter, 1/10 of a km) even in wooded areas. 

So I am asking you again to consider increasing the distance resolution. It is not a terribly big deal for me since I have the knowledge to edit and recompile the code but I am sure that many other, non-vocal people who are not programmers would like to see this change. 

Regards and thank you for your work!

**Comment by tumic0** [comment]
> The advent of dual-frequency devices has definitely pushed the reliability of distance measurement way below 1/10 of a mile (or, for that matter, 1/10 of a km) even in wooded areas.

Has it? Show me some studies/measurements. Even with the current "state of the art" consumer GPSs with an accuracy of ~1m you [won't get errors under 1%](https://pmc.ncbi.nlm.nih.gov/articles/PMC4786863/). If you have the correct sampling. With insufficient sampling, you may get opposite - underestimated - results. The usual slight overestimation is "compensated" by the fact that GPXSee shows the 2D distance as distance, the real 3D distance is usually little bit higher (you can compute the 3D distance from the elevations, but the error is high due to the high elevation error), but for any "real life" track longer than 1km (which is the treshold where GPXSee switches from meters to kilometers) you simply won't get an accuracy of 10m which is the "next digit".

But let's make a deal. Get a professional [measuring wheel](https://www.amazon.com/Measuring-Wheels/b?ie=UTF8&node=3753421), measure your real outdoor track (at least 3km) with it and than run/walk it several times (at least 5x) while recording it with your consumer grade GPS device. If your GPS distance to measuring wheel distance difference will be under 10m for all of your measurements, I will increase the precision for the distance in GPXSee.

**Comment by tumic0** [comment]
I'm ok with 15m difference :-).

I will trust you and not demand a notarized proof, however it would be nice to see the data as there are generally not much such measurements available as far as I have googled.

**Comment by harrywalther** [comment]
Don't worry, I have no interest in falsifying data. It's just a nice little nerdy experiment and even if it doesn't turn out the way I anticipate I will still have learned something from it. 

I'll send you a KML of the chosen course and the wheeled distance once I have it and, if you're interested enough, the fit tracks.

**Comment by harrywalther** [comment]
Hello again,
my first measurement is done.

I got myself a Zozen wheel as per your link and chose a track. It is an almost flat loop course with about 3m elevation gain per Google Earth (so negligible for calculations) and a length of 1823m  per a Google Earth plot. 
I wheeled it twice (due to having to avoid bike traffic) once clockwise, once counterclockwise, guiding the wheel on my right side.  The inside loop measured 1816m, the outside 1829m, averaging 1822.5m. (The path is an estimated 2m wide on average, so that sounds right.)

This is almost too good of a match, but I tried hard to be as accurate as possible and minimize skipping of the wheel. 

I ran the loop twice with a Garmin Forerunner 955 and the GPS set to all systems + dual band, fit track attached. The raw track shows a length of 3653m (I started the GPS before I got the best possible fix - it was cold! And stopped it a bit too late)

So, first test:  3653m vs 3645m  - 8m difference with the fit track, not unexpectedly, the longer one.

I owe you four more, which may take some time because it's not a particularly exciting run...

[acc_test_1.fit.zip](https://github.com/user-attachments/files/17578158/acc_test_1.fit.zip)

**Comment by tumic0** [comment]
Nice work! While I'm still a little bit skeptical if you get this precision in a general case - you have chosen an as ideal as possible track/measurement (few corners, no vegetation, no elevation) - it proves there are situations where a higher precision can be achieved. In 244a7670e77d46ea395c6506083fc6f15f6f415a I have increased the precision for tracks < 10km (mi/nmi) to two digits, I hope we both agree that for longer tracks you wan't almost never achieve the two digits precision even under ideal conditions.

**Comment by harrywalther** [comment]
Agreed and thank you! 

I was going to add that this is an almost ideal scenario (there are a few trees though) and my claim is strictly for GPS with dual band while running, which spreads out the data points more than walking and thus introduces less distance error.

I had to choose something simple due to the area I live in. If you checked the environment of the track then you will have seen that there is virtually no dense tree cover and any trails available are in quite steep terrain, which would introduce the complication of 3d distance. Also, the trails are either very rocky or sand - or both. Very bad for wheeling accurately.

It's not called the High Desert for nothing!

Would you like additional tracks? Even if you don't insist I will still repeat the run (maybe not 4 more times though) and if you are interested will post the results here. Since I have that wheel now I should put it to some use sometimes.

**Comment by tumic0** [comment]
> Would you like additional tracks? Even if you don't insist I will still repeat the run (maybe not 4 more times though) and if you are interested will post the results here. Since I have that wheel now I should put it to some use sometimes.

It would be nice to have at least one additional run on the same track to exclude the accuracy wasn't pure fortune. And if you are prepared to do more for science (and play with your new toy ;-) ), than a longer track from the area somewhere north-east of Marlette Lake would be great to see what happens when the landscape changes to something less GPS-friendly.

In any case, you already "won" and the next version of GPXSee will contain the increased precision anyway :-) I'm closing this issue now, but if you come with more data, just put it here.

**Comment by harrywalther** [comment]
Second run; this time 3 loops.

fit track is 5472 m vs 5467.5 m wheeled (3*1822.5)

I'll see that I can measure something on a real single track in the pines, but winter has already started so that may take a good while.

[acc_test_2.fit.zip](https://github.com/user-attachments/files/17652725/acc_test_2.fit.zip)
