### ISSUE TITLE
Switching to full or normal screen view leads to MapView's reset (center+zoom)

### ISSUE THREAD

**Issue by sikmir** [tumic0/GPXSee#74]
Some use case from real life:
1. Open some long track
2. Switch to fullscreen mode
3. Move/Zoom in to some part of the track for details
4. ...want to choose another map
5. Switch to normal mode to change map
6. ...MapView reset:(

It's really confusing.

**Comment by tumic0** [comment]
Yes, every resizing of the map widget triggers a content "re-fitting". The problem is, it is quiet hard to distinguish the resize events. For some of them, (eg. widget show on map load), the "re-fitting" must be always done. I have already been fiddling with the resize/re-fit code in the past with no success...

**Comment by sikmir** [comment]
I don't know if that will help, but this problem is solved in QMapShack/QLandkarteGT. Have you looked at its code?

**Comment by tumic0** [comment]
Well, the problem is more about the decision when to resize and when not, than how to technically do it. Additionally it would introduce a lot of "ugly" if-else code as it seems it is not possible to find some universal rule. So my motivation to do something about it is quiet low...

Btw. - in your case you can switch the map using the keyboard shortcuts, so there is no need to switch from/to fullscreen.

**Comment by sikmir** [comment]
> Btw. - in your case you can switch the map using the keyboard shortcuts, so there is no need to switch from/to fullscreen.

Yes, I know. But there are a lot of other cases. For example, I use tiling window manager (i3wm), so each time I open new window, ALL other ones are resized, and "re-fitting" occurs. It's painful:)

**Comment by sikmir** [comment]
Well done!:+1: That's great news. GPXSee is almost perfect now.
