### ISSUE TITLE
directories/default paths

### ISSUE THREAD

**Issue by j-schneid** [tumic0/GPXSee#90]
I'm on Windows 10 pro and I am a bit confused about the use of default paths in GPXSee.

- When I want to open a track file the dialogue always starts in the program directory. It should possibly (best) remember the last used path or (2) at least start in the user's profile or documents folder. In a program folder there should never be any data a user wants to open.
- The location of the tile folder should be configurable or better be automatically in the default location of the OS. It is a kind of cache, so on Windows it would comply to system standards if it were <userprofile>\appdata\...
- There is a "User override directory: C:/Users/<profile>/GPXSee". It is translated "Benutzerverzeichnis" to German which means simply "user directory". To be honest I don't know a better translation that includes the meaning of "override". Anyway a little hint in the GUI would be helpful to find out what this is meant for. When I add an .xml file in C:/Users/<profile>/GPXSee/maps only this one is displayed in the menu, but none of the original files in the program folder. Is this intended?

**Comment by tumic0** [comment]
1. The default data open directory is now the "current directory", which I admit, is most probably not the right path for a GUI application. User's $HOME (%HOMEPATH%) is probably a better choice, I will have a look at it. Whether to remember the last open directory is another question. Personally, I'm not a big fan of such behavior, but you are not the first one requesting it, so I will maybe give it a try...
2. The tile folder is in the user's application folder, which is generally the right place. On Windows it is %HOMEPATH%\GPXSee at the moment. Changing it to the "more correct" %HOMEPATH%\AppData\GPXsee is for sure possible, it would however negatively affect all users that would upgrade to the new version...
3. The override directory is %HOMEPATH%\GPXSee. It is named override because all the files there override the global files in the application folder. There is some info about this on the GPXSee homepage (http://www.gpxsee.org/doc.html)

**Comment by tumic0** [comment]
bda24d90917db9ae9dc892dfc06f35a358136203 unifies the default open directory to $HOME/%HOMEPATH% on all platforms (worked fine on linux even before the change). The last open directory stays however NOT remembered across multiple program runs as it makes no sense in my "directory-based workflow".

The application folder on windows will not be touched until some major version upgrade.
